// Brand/drug names are intentionally left untranslated in both languages —
// packaging and prescriptions use the Latin-script brand name regardless of
// locale, so translating them would hurt usability, not help it.
export const RAPID_INSULINS = [
  "NovoRapid (Aspart)",
  "Apidra (Glulisine)",
  "Humalog (Lispro)",
  "Fiasp",
  "Actrapid (Regular/Short-acting)",
  "Other rapid/short-acting",
];

export const BASAL_INSULINS = [
  "Lantus (Glargine)",
  "Levemir (Detemir)",
  "Tresiba (Degludec)",
  "Toujeo",
  "Basaglar",
  "Insulatard (NPH)",
  "Other basal/long-acting",
];

export const PILL_OPTIONS = [
  "Metformin",
  "Glimepiride",
  "Gliclazide",
  "Sitagliptin",
  "Empagliflozin",
  "Dapagliflozin",
  "Pioglitazone",
  "Repaglinide",
  "Acarbose",
  "Other pill",
];

export const DIABETES_TYPE_IDS = ["type1", "type2", "gestational", "other"] as const;

// Display price, shown on the web/Paymob, Android/Play Billing, and
// iOS/StoreKit paths alike — all three are priced the same ($5). Each
// processor is configured independently (Paymob's PAYMOB_AMOUNT_CENTS env
// var, the premium_lifetime price in Play Console, the price set for the
// product in App Store Connect) — this constant only controls the text
// shown in the app, not what any processor actually charges. Keep all
// three in sync by hand if the price ever changes.
export const ONE_TIME_PRICE_DISPLAY = "$5";
export const TRIAL_DAYS = 2;

// Full UI-chrome translation (EN/AR), RTL-tested on every screen. Per the
// original design handoff's stated scope, the food database (FOOD_DB) and
// brand/drug names above are out of scope — those are a content-catalog
// translation project, not UI chrome.
export const STRINGS = {
  en: {
    nav: {
      setup: "Setup",
      tips: "Tips",
      community: "Community",
      home: "Home",
      overview: "Overview",
      calculator: "Calculator",
      history: "History",
      care: "Care",
      pro: "PRO",
      free: "FREE",
      age: (age: number | string) => `Age ${age}`,
    },
    common: {
      continueBtn: "Continue",
      savingBtn: "Saving…",
      somethingWrong: "Something went wrong.",
      loading: "Loading…",
      dash: "—",
      back: "Back",
      cancel: "Cancel",
    },
    auth: {
      appTagline: "Personalized carb ratio and insulin dose calculator.",
      language: "Language",
      login: "Log in",
      signup: "Sign up",
      usernameLabel: "Username",
      usernamePlaceholder: "e.g. mona_h",
      passwordLabel: "Password",
      emailLabel: "Email",
      emailHint: "Required — lets you reset your password if you forget it",
      emailPlaceholder: "you@example.com",
      fillRequiredFields: "Please fill in all required fields.",
      passwordTooShort: "Password must be at least 8 characters.",
      pleaseWait: "Please wait…",
      forgotPassword: "Forgot password?",
      disclaimer:
        "This app supports diabetes self-management and does not replace medical advice. Always confirm dosing decisions with your care team.",
    },
    onboarding: {
      title: "Set up your profile",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Your name",
      genderLabel: "Gender",
      female: "Female",
      male: "Male",
      ageLabel: "Age",
      agePlaceholder: "e.g. 29",
      unitsLabel: "Preferred glucose units",
      diagnosisDateLabel: "When were you diagnosed?",
      diabetesTypeLabel: "Type of diabetes",
      treatmentModeLabel: "How do you manage your diabetes?",
      insulin: "Insulin",
      pills: "Pills",
      both: "Both",
      insulinRegimenTitle: "Insulin regimen",
      deliveryLabel: "How is your insulin delivered?",
      injections: "Injections (MDI)",
      pump: "Insulin pump",
      pumpInsulinLabel: "Insulin used in pump",
      pumpInsulinHint: "Pumps use rapid-acting insulin only",
      bolusUnitsLabel: "Bolus (meal) units per day",
      bolusUnitsHint: "Optional — from your pump history, total meal/correction boluses in a typical day",
      bolusPlaceholder: "e.g. 40 (optional)",
      basalBackgroundLabel: "Basal (background) units per day",
      basalBackgroundHint: "Total basal delivered by the pump in a typical day",
      basalPumpPlaceholder: "e.g. 20",
      rapidInsulinLabel: "Rapid-acting (mealtime) insulin",
      rapidUnitsLabel: "Total rapid units per day",
      rapidUnitsHint: "Sum of all mealtime doses across a typical day",
      rapidPlaceholder: "e.g. 60",
      basalInsulinLabel: "Basal (long-acting) insulin",
      basalUnitsLabel: "Total basal units per day",
      basalPlaceholder: "e.g. 35",
      rapidActionMinutesLabel: "Insulin action duration (minutes)",
      rapidActionMinutesHint: "How long a dose of your rapid-acting insulin stays active — ask your doctor if unsure",
      oralMedicationTitle: "Oral medication(s)",
      reviewIntro:
        "Based on your total daily insulin dose, here are your calculated ratios (500 rule for carb ratio, 1500 rule for insulin sensitivity):",
      totalDailyDoseLabel: "Total daily dose",
      carbRatioLabel: "Carb ratio",
      sensitivityLabel: "Sensitivity (ISF)",
      reviewSummary: (carbRatio: string, isf: string) =>
        `1 unit of rapid insulin covers about ${carbRatio}g of carbohydrate, and lowers blood glucose by about ${isf} mg/dL.`,
      doctorOverrideLabel: "My doctor gave me different numbers",
      on: "On",
      off: "Off",
      carbRatioManualLabel: "Carb ratio (g per unit)",
      isfManualLabel: "ISF (mg/dL per unit)",
      doctorOverrideRequired: "Enter both values your doctor gave you to continue.",
      pillsOnlyNotice:
        "Since you're managing with oral medication only, dose calculations are skipped — you can still log meals and glucose readings for your history.",
      finishSetup: "Finish setup",
      saveError: "Could not save your profile.",
    },
    dashboard: {
      overviewTab: "Overview",
      calculatorTab: "Calculator",
      logYourDayTitle: "Log Your Day",
      timeInRangeLabel: "Today's Time in Range",
      green: "Green",
      fair: "Fair",
      needsAttention: "Needs attention",
      noData: "No data",
      streakLabel: "Day Streak",
      pointsLabel: "Action Points",
      quickLogTitle: "Quick Log",
      logBGBtn: "+ Log BG",
      currentBGLabel: "Current BG",
      insulinTakenLabel: "Insulin Taken",
      yourHistoryTitle: "Your History",
      viewAllBtn: "View all",
      nothingLoggedYet: "Nothing logged yet.",
      unlockPremiumTitle: "Unlock Premium",
      unlockPremiumDesc: "Unlimited history, PDF reports, trend insights.",
      subscribeBtn: "Subscribe",
      bgBadge: (v: number | string) => `BG ${v}`,
      carbsBadge: (v: number | string) => `Carbs ${v}g`,
      insulinBadge: (v: number | string) => `Insulin ${v}u`,
      currentGlucoseLabel: "Current glucose",
      logGlucoseBtn: "+ Log Glucose",
      logMealDoseBtn: "+ Log Meal / Dose",
      lastLogged: (rel: string) => `Last logged ${rel}`,
      noReadingsYet: "No readings logged yet",
      activeInsulinLabel: "Active Insulin",
      unitsShort: "Units",
      carbsOnBoardLabel: "Carbs On Board",
      gramsUnitLabel: "Grams",
      recentActivityTitle: "Recent Activity",
      exportReportTitle: "Export Medical PDF Reports",
      exportReportDesc: "Share detailed trends directly with your doctor",
      trendTitle: "Glucose Trend (24 Hours)",
      targetRangeLabel: (low: number | string, high: number | string) => `Target: ${low}-${high}`,
      notEnoughDataChart: "Not enough readings today yet",
      risingLabel: "Rising",
      stableLabel: "Stable",
      fallingLabel: "Falling",
      normalBadge: "Normal",
      bolusDoseLabel: "Bolus dose",
      fingerstickLabel: "Fingerstick check",
      rapidInsulinLabel: "Rapid Insulin",
      glucoseLabel: "Glucose",
      viewAllArrow: "View All →",
    },
    calculator: {
      noInsulinTitle: "No insulin dosing on file",
      noInsulinDesc: "You can still log carbs and glucose. Add insulin info in Setup to unlock dose calculations.",
      mealTab: "Meal",
      mealCorrTab: "Meal+Corr.",
      correctionTab: "Correction only",
      hypoTab: "Low BG (hypo)",
      mealItemsTitle: "Meal items",
      noItemsYet: "No items added yet.",
      addFoodFromList: "+ Add food from list",
      addYourOwnFood: "+ Add your own food",
      totalCarbsLabel: "Total carbs",
      currentBGLabel: (unit: string) => `Current BG (${unit})`,
      currentBGOptionalHint: "Optional — just for your records",
      targetBGLabel: (unit: string) => `Target BG (${unit})`,
      notesLabel: "Notes",
      notesPlaceholder: "Anything worth remembering about this entry… (optional)",
      mealDoseLabel: "Meal dose",
      mealCorrDoseLabel: "Meal + correction dose",
      correctionDoseLabel: "Correction dose",
      hypoCarbsLabel: "Carbs needed (low BG)",
      treatLowFirst: "Treat the low first — recheck BG in 15 minutes.",
      units: "units",
      gCarbs: "g carbs",
      logThisBtn: "Log this",
      savedBtn: "Saved ✓",
      reviewMealTitle: "Review before logging",
      confirmLogBtn: "Confirm & log",
      addAFoodTitle: "Add a food",
      searchPlaceholder: "Search food… e.g. rice, banana",
      allCategory: "All",
      noFoodsFound: "No foods found.",
      mineTag: "mine",
      addYourOwnFoodTitle: "Add your own food",
      foodNameLabel: "Food name",
      foodNamePlaceholder: "e.g. Mom's stuffed cabbage",
      portionLabel: "Portion size",
      portionPlaceholder: "e.g. 1 roll (80g)",
      carbsPerPortionLabel: "Carbs (g) per portion",
      carbsPlaceholder: "e.g. 18",
      addToMyFoods: "Add to my foods",
      carbsUnit: (g: number | string) => `${g}g carbs`,
      mealCorrSummary: (meal: string, corr: string) => `Meal ${meal}u + correction ${corr}u`,
      myFoodsCategory: "My Foods",
      onePortionFallback: "1 portion",
      gramsShort: (g: number | string) => `${g}g`,
    },
    history: {
      timeInRangeTitle: "Time in range",
      noReadingsPeriod: "No glucose readings logged in this period yet.",
      low: "Low",
      inRange: "In Range",
      high: "High",
      logBGReadingBtn: "+ Log BG reading",
      downloadReportBtn: "Download report",
      filterAll: "All",
      filterMeals: "Meals",
      filterDoses: "Doses",
      filterGlucose: "Glucose",
      nothingLoggedMessage: "Nothing logged yet. Doses and readings you log from the Calculator will show up here.",
      hiddenEntries: (n: number) => `${n} more entries hidden`,
      freeAccountsMessage: "Free accounts see your last 15 entries. Go Premium for unlimited history and export.",
      seePremiumBtn: "See Premium",
      logGlucoseTitle: "Log a glucose reading",
      bloodGlucoseLabel: (unit: string) => `Blood glucose (${unit})`,
      saveReadingBtn: "Save reading",
      mealDoseType: "Meal dose",
      mealCorrType: "Meal + correction",
      correctionType: "Correction dose",
      hypoType: "Low BG treated",
      bgType: "Glucose reading",
      today: "Today",
      targetArrow: (v: number | string) => ` → target ${v}`,
      bgReading: (v: number | string) => `BG ${v}`,
      whenLabel: "Date & time",
      editEntryTitle: "Edit entry",
      doseLabel: "Dose (units)",
      saveChangesBtn: "Save changes",
      deleteEntryBtn: "Delete entry",
      deleteConfirmMessage: "Delete this entry? This can't be undone.",
      deleteConfirmBtn: "Yes, delete",
    },
    tips: {
      title: "Tips for you",
      subtitle: "Based on what you've logged recently.",
      emptyTitle: "Not enough data yet",
      emptyDesc: "Log a few more meals and glucose readings and we'll surface personalized tips here.",
      timeInRangeHighTip: (pct: number) =>
        `Your readings have been high ${pct}% of the time over the last 14 days — worth reviewing your correction doses with your care team.`,
      timeInRangeLowTip: (pct: number) =>
        `Your readings have been low ${pct}% of the time over the last 14 days — talk to your care team about your ISF or carb ratio.`,
      timeOfDayTip: (window: string, pct: number) => `Your BG tends to run high after ${window} (${pct}% of readings in that window).`,
      loggingGapTip: "You haven't logged anything in a couple of days — log a reading to keep your streak going.",
      windowBreakfast: "breakfast",
      windowLunch: "lunch",
      windowDinner: "dinner",
      windowOther: "other times",
    },
    community: {
      title: "Community",
      subtitle: "See what other GlucoDose users are sharing.",
      emptyTitle: "No posts yet",
      emptyDesc: "Be the first to share something with the community.",
      newPostBtn: "+ New post",
      composeTitle: "Share with the community",
      composePlaceholder: "Share a tip, a win, or a question…",
      postBtn: "Post",
      postError: "Could not post. Please try again.",
      justNow: "Just now",
      minutesAgo: (n: number) => `${n}m ago`,
      hoursAgo: (n: number) => `${n}h ago`,
      daysAgo: (n: number) => `${n}d ago`,
    },
    share: {
      title: "Share your progress",
      subtitle: "Send your stats to a friend or your care team.",
      streakLine: (n: number) => `🔥 ${n}-day streak`,
      pointsLine: (n: number) => `⭐ ${n} action points`,
      timeInRangeLine: (pct: number) => `🎯 ${pct}% time in range (last 14 days)`,
      shareBtn: "Share",
      copiedMsg: "Copied to clipboard!",
    },
    setup: {
      setupRatiosTitle: "Setup & Ratios",
      usernameLabel: "Username",
      emailLabel: "Email",
      addEmailBtn: "+ Add email",
      genderLabel: "Gender",
      ageLabel: "Age",
      dateDiagnosedLabel: "Date diagnosed",
      diabetesTypeLabel: "Diabetes type",
      glucoseUnitsLabel: "Glucose units",
      treatmentLabel: "Treatment",
      deliveryLabel: "Delivery",
      pillsLabel: "Pills",
      autoRatiosTitle: "Auto-Ratios",
      carbRatioTDDLabel: "Carb ratio (TDD)",
      insulinSensitivityLabel: "Insulin sensitivity",
      recalculateBtn: "Recalculate",
      doctorValuesNote: "Using your doctor's custom values.",
      unlockPremiumTitle: "Unlock Premium",
      unlockPremiumDesc: "Unlimited history, PDF reports, trend insights.",
      subscribeBtn: "Subscribe",
      editTreatmentBtn: "Edit treatment info",
      logoutBtn: "Log out",
      emailModalTitle: "Email for password reset",
      emailModalHint: "Used only to send you a password-reset link if you forget your password.",
      saveEmailBtn: "Save email",
      emailSaveError: "Could not save email.",
      privacyPolicyLink: "Privacy Policy",
      dangerZoneTitle: "Danger zone",
      deleteAccountBtn: "Delete account",
      deleteAccountConfirmMessage:
        "This permanently deletes your account and everything in it — profile, logged readings, doses, and history. This can't be undone.",
      deleteAccountConfirmBtn: "Yes, delete my account",
      deleteAccountError: "Could not delete account.",
    },
    premium: {
      title: "GlucoDose Premium",
      subtitle: "Everything you need to manage diabetes with confidence.",
      trialActive: (days: number) => `Free trial active — ${days} day${days === 1 ? "" : "s"} left`,
      trialSubtitle: "Subscribe below to keep using GlucoDose after your trial ends.",
      trialEnded: "Your free trial has ended — subscribe to keep using GlucoDose",
      paymentReceived: "Payment received — confirming…",
      checkoutCancelled: "Checkout cancelled",
      onetimePurchaseLabel: "One-time purchase",
      payOnceMessage: "Pay once, keep Premium forever",
      startTrialBtn: (days: number) => `Start ${days}-day free trial`,
      unlockPremiumBtn: "Unlock Premium",
      paymentsSecureNote: "Payments are processed securely by Paymob.",
      premiumUnlockedTitle: "You're Premium",
      premiumUnlockedDesc: "Unlocked for life — unlimited history, export, and more.",
      startTrialError: "Could not start trial.",
      checkoutError: "Could not start checkout.",
      paymentsSecureNoteAndroid: "Payments are processed securely by Google Play.",
      paymentsSecureNoteApple: "Payments are processed securely by the App Store.",
      restorePurchasesBtn: "Restore purchases",
      restoreError: "Could not restore purchases. Please try again or contact support.",
      features: [
        "Full access to dose calculations and daily tracking",
        "Full searchable food database, unlimited history",
        "Export a PDF report for your doctor",
        "Trend insights across meals & glucose readings",
      ],
    },
    forgotPassword: {
      title: "Reset your password",
      description: "Enter the email on your account and we'll send you a link to reset your password.",
      emailLabel: "Email",
      sendResetLinkBtn: "Send reset link",
      sendingBtn: "Sending…",
      devModeNote: "Dev mode (no email provider configured) — reset link:",
      backToLogin: "Back to log in",
    },
    resetPassword: {
      title: "Set a new password",
      missingTokenMessage: "This link is missing its reset token. Request a new one from the forgot password page.",
      missingTokenError: "This reset link is missing its token.",
      passwordsDontMatch: "Passwords don't match.",
      passwordUpdatedMessage: "Password updated — taking you to your dashboard…",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm new password",
      resetPasswordBtn: "Reset password",
      backToLogin: "Back to log in",
    },
    privacy: {
      title: "Privacy Policy",
      lastUpdated: "Last updated: August 9, 2026",
      operatedBy: "GlucoDose is operated by HFarid Apps (\"we\", \"us\").",
      sections: [
        {
          heading: "Information we collect",
          body: "Account information: username, email address (optional, used only for password resets), and a securely hashed password — we never store your password in plain text. Health and profile information you choose to enter: age, gender, diabetes type, diagnosis date, insulin or medication regimen, and your carb ratio / insulin sensitivity factor. Logged entries: glucose readings, carbohydrate counts, insulin doses, and any notes you add, each with a timestamp. Payment information: if you purchase Premium, your payment is processed directly by Paymob — we never see or store your card details, only whether the payment succeeded.",
        },
        {
          heading: "How we use your information",
          body: "To provide the app's core features: calculating suggested doses, tracking your history, and showing your trends. To send a password-reset email if you request one. To process a one-time Premium purchase. We do not use your health data for advertising, and we do not sell your data to anyone.",
        },
        {
          heading: "Third-party services",
          body: "We use a small number of third-party services to run the app: Paymob for payment processing, Resend for transactional emails (like password resets), and a hosting/database provider to run the app and store your data securely. Each only receives the minimum information needed to do its job.",
        },
        {
          heading: "Data retention and deletion",
          body: "Your data is kept for as long as your account exists. You can permanently delete your account and everything in it — profile, logged entries, and history — at any time from Setup in the app. This action is immediate and cannot be undone.",
        },
        {
          heading: "Data security",
          body: "Passwords are hashed with bcrypt and never stored or compared in plain text. Sessions use signed, httpOnly cookies. All traffic to the app is encrypted (HTTPS).",
        },
        {
          heading: "Medical disclaimer",
          body: "GlucoDose is a self-management tool, not a substitute for professional medical advice. Dose calculations are estimates based on formulas you and your care team configure — always confirm dosing decisions with your doctor or diabetes care team.",
        },
        {
          heading: "Children's privacy",
          body: "GlucoDose is intended to be used by adults managing their own diabetes care, or by a parent/guardian managing a dependent's care. If you are a parent or guardian creating an account on behalf of a child, you are responsible for that account and consent to this policy on their behalf.",
        },
        {
          heading: "Changes to this policy",
          body: "If we make material changes to this policy, we'll update the \"last updated\" date above. Continued use of the app after a change means you accept the updated policy.",
        },
        {
          heading: "Contact us",
          body: "Questions about this policy or your data? Email heba@aosama.me.",
        },
      ],
    },
    support: {
      title: "Support",
      intro: "Need help with GlucoDose? We're happy to answer questions, fix bugs, or hear your feedback.",
      contactHeading: "Contact us",
      contactBody: "Email heba@aosama.me and we'll get back to you as soon as we can.",
      faqHeading: "Frequently asked questions",
      faq: [
        {
          q: "How does the free trial work?",
          a: `GlucoDose gives you a ${TRIAL_DAYS}-day free trial when you sign up, with full access to every feature. After the trial ends, a one-time Premium purchase (${ONE_TIME_PRICE_DISPLAY}) unlocks the app permanently — no subscription, no recurring charges.`,
        },
        {
          q: "How do I restore my Premium purchase?",
          a: "Open Premium from the menu and tap \"Restore Purchases.\" This works on the same platform (App Store or Google Play) you originally purchased on.",
        },
        {
          q: "How do I delete my account or data?",
          a: "Go to Setup in the app and tap \"Delete account.\" This permanently removes your profile, logged entries, and history, and cannot be undone.",
        },
        {
          q: "I found a bug or have a feature request.",
          a: "Email us at heba@aosama.me with as much detail as you can (what you were doing, what you expected, and what happened instead) — screenshots help a lot.",
        },
      ],
    },
  },
  ar: {
    nav: {
      setup: "الإعدادات",
      tips: "نصائح",
      community: "المجتمع",
      home: "الرئيسية",
      overview: "نظرة عامة",
      calculator: "الحاسبة",
      history: "السجل",
      care: "الرعاية",
      pro: "PRO",
      free: "مجاني",
      age: (age: number | string) => `العمر ${age}`,
    },
    common: {
      continueBtn: "متابعة",
      savingBtn: "جارٍ الحفظ…",
      somethingWrong: "حدث خطأ ما.",
      loading: "جارٍ التحميل…",
      dash: "—",
      back: "رجوع",
      cancel: "إلغاء",
    },
    auth: {
      appTagline: "حاسبة معامل الكارب وحساسية الأنسولين الخاصة بك.",
      language: "اللغة",
      login: "تسجيل الدخول",
      signup: "حساب جديد",
      usernameLabel: "اسم المستخدم",
      usernamePlaceholder: "مثال: mona_h",
      passwordLabel: "كلمة المرور",
      emailLabel: "البريد الإلكتروني",
      emailHint: "إلزامي — يتيح لك استعادة كلمة المرور إذا نسيتها",
      emailPlaceholder: "you@example.com",
      fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة.",
      passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
      pleaseWait: "يرجى الانتظار…",
      forgotPassword: "نسيت كلمة المرور؟",
      disclaimer:
        "يساعدك هذا التطبيق على إدارة مرض السكري بنفسك، ولا يغني عن الاستشارة الطبية. تأكدي دائماً من قرارات الجرعات مع فريقك الطبي.",
    },
    onboarding: {
      title: "أنشئي ملفك الشخصي",
      fullNameLabel: "الاسم الكامل",
      fullNamePlaceholder: "اسمك",
      genderLabel: "الجنس",
      female: "أنثى",
      male: "ذكر",
      ageLabel: "العمر",
      agePlaceholder: "مثال: 29",
      unitsLabel: "وحدة قياس السكر المفضلة",
      diagnosisDateLabel: "متى تم تشخيصك؟",
      diabetesTypeLabel: "نوع مرض السكري",
      treatmentModeLabel: "كيف تديرين مرض السكري؟",
      insulin: "أنسولين",
      pills: "حبوب",
      both: "كلاهما",
      insulinRegimenTitle: "نظام الأنسولين",
      deliveryLabel: "كيف يُعطى الأنسولين؟",
      injections: "حقن (متعددة الجرعات)",
      pump: "مضخة أنسولين",
      pumpInsulinLabel: "الأنسولين المستخدم في المضخة",
      pumpInsulinHint: "تستخدم المضخات الأنسولين سريع المفعول فقط",
      bolusUnitsLabel: "وحدات الوجبة (بولس) يومياً",
      bolusUnitsHint: "اختياري — من سجل مضختك، إجمالي جرعات الوجبات والتصحيح في يوم معتاد",
      bolusPlaceholder: "مثال: 40 (اختياري)",
      basalBackgroundLabel: "الوحدات الأساسية يومياً",
      basalBackgroundHint: "إجمالي الجرعة الأساسية التي تعطيها المضخة في يوم معتاد",
      basalPumpPlaceholder: "مثال: 20",
      rapidInsulinLabel: "الأنسولين سريع المفعول (وقت الوجبات)",
      rapidUnitsLabel: "إجمالي الوحدات سريعة المفعول يومياً",
      rapidUnitsHint: "مجموع جرعات الوجبات في يوم معتاد",
      rapidPlaceholder: "مثال: 60",
      basalInsulinLabel: "الأنسولين طويل المفعول (الأساسي)",
      basalUnitsLabel: "إجمالي الوحدات الأساسية يومياً",
      basalPlaceholder: "مثال: 35",
      rapidActionMinutesLabel: "مدة فاعلية الأنسولين (بالدقائق)",
      rapidActionMinutesHint: "المدة التي تبقى فيها جرعة الأنسولين سريع المفعول نشطة — اسألي طبيبك إذا لم تكوني متأكدة",
      oralMedicationTitle: "الأدوية عن طريق الفم",
      reviewIntro:
        "بناءً على إجمالي جرعة الأنسولين اليومية، إليك النسب المحسوبة (قاعدة 500 لمعامل الكارب، وقاعدة 1500 لحساسية الأنسولين):",
      totalDailyDoseLabel: "إجمالي الجرعة اليومية",
      carbRatioLabel: "معامل الكارب",
      sensitivityLabel: "الحساسية (ISF)",
      reviewSummary: (carbRatio: string, isf: string) =>
        `تغطي كل وحدة أنسولين سريع حوالي ${carbRatio} جم من الكربوهيدرات، وتخفض سكر الدم بحوالي ${isf} ملغ/دل.`,
      doctorOverrideLabel: "طبيبي أعطاني أرقاماً مختلفة",
      on: "مفعّل",
      off: "متوقف",
      carbRatioManualLabel: "معامل الكارب (جم لكل وحدة)",
      isfManualLabel: "ISF (ملغ/دل لكل وحدة)",
      doctorOverrideRequired: "أدخلي كلا القيمتين اللتين أعطاك إياهما طبيبك للمتابعة.",
      pillsOnlyNotice:
        "بما أنك تدارين حالتك بالأدوية الفموية فقط، يتم تخطي حسابات الجرعات — يمكنك مع ذلك تسجيل الوجبات وقراءات السكر في سجلك.",
      finishSetup: "إنهاء الإعداد",
      saveError: "تعذر حفظ ملفك الشخصي.",
    },
    dashboard: {
      overviewTab: "نظرة عامة",
      calculatorTab: "الحاسبة",
      logYourDayTitle: "سجّلي يومك",
      timeInRangeLabel: "الوقت ضمن النطاق اليوم",
      green: "جيد",
      fair: "متوسط",
      needsAttention: "يحتاج انتباه",
      noData: "لا توجد بيانات",
      streakLabel: "أيام متتالية",
      pointsLabel: "نقاط النشاط",
      quickLogTitle: "تسجيل سريع",
      logBGBtn: "+ تسجيل السكر",
      currentBGLabel: "السكر الحالي",
      insulinTakenLabel: "الأنسولين المأخوذ",
      yourHistoryTitle: "سجلك",
      viewAllBtn: "عرض الكل",
      nothingLoggedYet: "لم يتم تسجيل أي شيء بعد.",
      unlockPremiumTitle: "افتحي بريميوم",
      unlockPremiumDesc: "سجل غير محدود، تقارير PDF، ورؤى وتحليلات.",
      subscribeBtn: "اشتراك",
      bgBadge: (v: number | string) => `السكر ${v}`,
      carbsBadge: (v: number | string) => `كارب ${v}جم`,
      insulinBadge: (v: number | string) => `أنسولين ${v}و`,
      currentGlucoseLabel: "السكر الحالي",
      logGlucoseBtn: "+ تسجيل السكر",
      logMealDoseBtn: "+ تسجيل وجبة / جرعة",
      lastLogged: (rel: string) => `آخر تسجيل ${rel}`,
      noReadingsYet: "لا توجد قراءات مسجلة بعد",
      activeInsulinLabel: "الأنسولين النشط",
      unitsShort: "وحدة",
      carbsOnBoardLabel: "الكارب النشط",
      gramsUnitLabel: "جرام",
      recentActivityTitle: "النشاط الأخير",
      exportReportTitle: "تصدير تقرير طبي PDF",
      exportReportDesc: "شاركي التفاصيل مباشرة مع طبيبك",
      trendTitle: "اتجاه السكر (24 ساعة)",
      targetRangeLabel: (low: number | string, high: number | string) => `الهدف: ${low}-${high}`,
      notEnoughDataChart: "لا توجد قراءات كافية اليوم بعد",
      risingLabel: "يرتفع",
      stableLabel: "مستقر",
      fallingLabel: "ينخفض",
      normalBadge: "طبيعي",
      bolusDoseLabel: "جرعة بولس",
      fingerstickLabel: "قياس بالإصبع",
      rapidInsulinLabel: "أنسولين سريع",
      glucoseLabel: "سكر",
      viewAllArrow: "عرض الكل ←",
    },
    calculator: {
      noInsulinTitle: "لا يوجد نظام أنسولين مسجل",
      noInsulinDesc: "لا يزال بإمكانك تسجيل الكارب والسكر. أضيفي بيانات الأنسولين في الإعدادات لتفعيل حساب الجرعات.",
      mealTab: "وجبة",
      mealCorrTab: "وجبة+تصحيح",
      correctionTab: "تصحيح فقط",
      hypoTab: "انخفاض السكر",
      mealItemsTitle: "عناصر الوجبة",
      noItemsYet: "لم تتم إضافة عناصر بعد.",
      addFoodFromList: "+ إضافة طعام من القائمة",
      addYourOwnFood: "+ إضافة طعامك الخاص",
      totalCarbsLabel: "إجمالي الكارب",
      currentBGLabel: (unit: string) => `السكر الحالي (${unit})`,
      currentBGOptionalHint: "اختياري — لسجلاتك فقط",
      targetBGLabel: (unit: string) => `السكر المستهدف (${unit})`,
      notesLabel: "ملاحظات",
      notesPlaceholder: "أي شيء يستحق التذكر عن هذا التسجيل… (اختياري)",
      mealDoseLabel: "جرعة الوجبة",
      mealCorrDoseLabel: "جرعة الوجبة + التصحيح",
      correctionDoseLabel: "جرعة التصحيح",
      hypoCarbsLabel: "الكارب المطلوب (انخفاض السكر)",
      treatLowFirst: "عالجي الانخفاض أولاً — أعيدي فحص السكر بعد 15 دقيقة.",
      units: "وحدة",
      gCarbs: "جم كارب",
      logThisBtn: "تسجيل",
      savedBtn: "تم الحفظ ✓",
      reviewMealTitle: "مراجعة قبل التسجيل",
      confirmLogBtn: "تأكيد وتسجيل",
      addAFoodTitle: "إضافة طعام",
      searchPlaceholder: "ابحثي عن طعام… مثال: أرز، موز",
      allCategory: "الكل",
      noFoodsFound: "لا توجد أطعمة مطابقة.",
      mineTag: "خاصتي",
      addYourOwnFoodTitle: "إضافة طعامك الخاص",
      foodNameLabel: "اسم الطعام",
      foodNamePlaceholder: "مثال: محشي أمي",
      portionLabel: "حجم الحصة",
      portionPlaceholder: "مثال: قطعة واحدة (80جم)",
      carbsPerPortionLabel: "الكارب (جم) لكل حصة",
      carbsPlaceholder: "مثال: 18",
      addToMyFoods: "إضافة إلى أطعمتي",
      carbsUnit: (g: number | string) => `${g}جم كارب`,
      mealCorrSummary: (meal: string, corr: string) => `وجبة ${meal}و + تصحيح ${corr}و`,
      myFoodsCategory: "أطعمتي",
      onePortionFallback: "حصة واحدة",
      gramsShort: (g: number | string) => `${g}جم`,
    },
    history: {
      timeInRangeTitle: "الوقت ضمن النطاق",
      noReadingsPeriod: "لا توجد قراءات سكر مسجلة في هذه الفترة بعد.",
      low: "منخفض",
      inRange: "ضمن النطاق",
      high: "مرتفع",
      logBGReadingBtn: "+ تسجيل قراءة سكر",
      downloadReportBtn: "تحميل التقرير",
      filterAll: "الكل",
      filterMeals: "الوجبات",
      filterDoses: "الجرعات",
      filterGlucose: "السكر",
      nothingLoggedMessage: "لم يتم تسجيل أي شيء بعد. الجرعات والقراءات التي تسجلينها من الحاسبة ستظهر هنا.",
      hiddenEntries: (n: number) => `${n} إدخالات إضافية مخفية`,
      freeAccountsMessage: "تعرض الحسابات المجانية آخر 15 إدخالاً فقط. اشتركي في بريميوم للسجل غير المحدود والتصدير.",
      seePremiumBtn: "عرض بريميوم",
      logGlucoseTitle: "تسجيل قراءة سكر",
      bloodGlucoseLabel: (unit: string) => `سكر الدم (${unit})`,
      saveReadingBtn: "حفظ القراءة",
      mealDoseType: "جرعة وجبة",
      mealCorrType: "وجبة + تصحيح",
      correctionType: "جرعة تصحيح",
      hypoType: "تم علاج انخفاض السكر",
      bgType: "قراءة سكر",
      today: "اليوم",
      targetArrow: (v: number | string) => ` ← الهدف ${v}`,
      bgReading: (v: number | string) => `السكر ${v}`,
      whenLabel: "التاريخ والوقت",
      editEntryTitle: "تعديل الإدخال",
      doseLabel: "الجرعة (وحدات)",
      saveChangesBtn: "حفظ التغييرات",
      deleteEntryBtn: "حذف الإدخال",
      deleteConfirmMessage: "هل تريدين حذف هذا الإدخال؟ لا يمكن التراجع عن هذا.",
      deleteConfirmBtn: "نعم، احذف",
    },
    tips: {
      title: "نصائح لك",
      subtitle: "بناءً على ما سجّلتِه مؤخراً.",
      emptyTitle: "لا توجد بيانات كافية بعد",
      emptyDesc: "سجّلي المزيد من الوجبات وقراءات السكر وستظهر لكِ نصائح مخصصة هنا.",
      timeInRangeHighTip: (pct: number) =>
        `كانت قراءاتك مرتفعة ${pct}% من الوقت خلال آخر 14 يوماً — يستحق مراجعة جرعات التصحيح مع فريق الرعاية.`,
      timeInRangeLowTip: (pct: number) =>
        `كانت قراءاتك منخفضة ${pct}% من الوقت خلال آخر 14 يوماً — تحدثي مع فريق الرعاية عن حساسية الأنسولين أو معامل الكارب.`,
      timeOfDayTip: (window: string, pct: number) => `يميل سكر الدم للارتفاع بعد ${window} (${pct}% من القراءات في هذه الفترة).`,
      loggingGapTip: "لم تسجّلي شيئاً منذ يومين — سجّلي قراءة للحفاظ على تتابعك.",
      windowBreakfast: "الإفطار",
      windowLunch: "الغداء",
      windowDinner: "العشاء",
      windowOther: "أوقات أخرى",
    },
    community: {
      title: "المجتمع",
      subtitle: "شاهدي ما يشاركه مستخدمو GlucoDose الآخرون.",
      emptyTitle: "لا توجد منشورات بعد",
      emptyDesc: "كوني أول من يشارك شيئاً مع المجتمع.",
      newPostBtn: "+ منشور جديد",
      composeTitle: "شاركي مع المجتمع",
      composePlaceholder: "شاركي نصيحة، إنجازاً، أو سؤالاً…",
      postBtn: "نشر",
      postError: "تعذر النشر. حاولي مرة أخرى.",
      justNow: "الآن",
      minutesAgo: (n: number) => `منذ ${n} د`,
      hoursAgo: (n: number) => `منذ ${n} س`,
      daysAgo: (n: number) => `منذ ${n} يوم`,
    },
    share: {
      title: "شاركي تقدمك",
      subtitle: "أرسلي إحصائياتك لصديقة أو فريق الرعاية.",
      streakLine: (n: number) => `🔥 ${n} يوماً متتالياً`,
      pointsLine: (n: number) => `⭐ ${n} نقطة نشاط`,
      timeInRangeLine: (pct: number) => `🎯 ${pct}% ضمن النطاق (آخر 14 يوماً)`,
      shareBtn: "مشاركة",
      copiedMsg: "تم النسخ إلى الحافظة!",
    },
    setup: {
      setupRatiosTitle: "الإعدادات والنسب",
      usernameLabel: "اسم المستخدم",
      emailLabel: "البريد الإلكتروني",
      addEmailBtn: "+ إضافة بريد إلكتروني",
      genderLabel: "الجنس",
      ageLabel: "العمر",
      dateDiagnosedLabel: "تاريخ التشخيص",
      diabetesTypeLabel: "نوع مرض السكري",
      glucoseUnitsLabel: "وحدة قياس السكر",
      treatmentLabel: "العلاج",
      deliveryLabel: "طريقة الإعطاء",
      pillsLabel: "الحبوب",
      autoRatiosTitle: "النسب التلقائية",
      carbRatioTDDLabel: "معامل الكارب (TDD)",
      insulinSensitivityLabel: "حساسية الأنسولين",
      recalculateBtn: "إعادة الحساب",
      doctorValuesNote: "يتم استخدام القيم الخاصة بطبيبك.",
      unlockPremiumTitle: "افتحي بريميوم",
      unlockPremiumDesc: "سجل غير محدود، تقارير PDF، ورؤى وتحليلات.",
      subscribeBtn: "اشتراك",
      editTreatmentBtn: "تعديل بيانات العلاج",
      logoutBtn: "تسجيل الخروج",
      emailModalTitle: "البريد الإلكتروني لاستعادة كلمة المرور",
      emailModalHint: "يُستخدم فقط لإرسال رابط استعادة كلمة المرور إذا نسيتها.",
      saveEmailBtn: "حفظ البريد الإلكتروني",
      emailSaveError: "تعذر حفظ البريد الإلكتروني.",
      privacyPolicyLink: "سياسة الخصوصية",
      dangerZoneTitle: "منطقة الخطر",
      deleteAccountBtn: "حذف الحساب",
      deleteAccountConfirmMessage:
        "سيؤدي هذا إلى حذف حسابك وكل ما فيه بشكل نهائي — الملف الشخصي، القراءات المسجلة، الجرعات، والسجل. لا يمكن التراجع عن هذا.",
      deleteAccountConfirmBtn: "نعم، احذفي حسابي",
      deleteAccountError: "تعذر حذف الحساب.",
    },
    premium: {
      title: "بريميوم GlucoDose",
      subtitle: "كل ما تحتاجينه لإدارة مرض السكري بثقة.",
      trialActive: (days: number) => `التجربة المجانية مفعّلة — تبقى ${days} ${days === 1 ? "يوم" : "أيام"}`,
      trialSubtitle: "اشتركي أدناه لمواصلة استخدام GlucoDose بعد انتهاء تجربتك.",
      trialEnded: "انتهت تجربتك المجانية — اشتركي لمواصلة استخدام GlucoDose",
      paymentReceived: "تم استلام الدفعة — جارٍ التأكيد…",
      checkoutCancelled: "تم إلغاء الدفع",
      onetimePurchaseLabel: "دفعة لمرة واحدة",
      payOnceMessage: "ادفعي مرة واحدة، واحتفظي ببريميوم للأبد",
      startTrialBtn: (days: number) => `ابدئي تجربة ${days === 1 ? "يوم واحد" : `${days} أيام`} مجانية`,
      unlockPremiumBtn: "افتحي بريميوم",
      paymentsSecureNote: "تتم معالجة المدفوعات بأمان عبر Paymob.",
      premiumUnlockedTitle: "أنتِ عضوة بريميوم",
      premiumUnlockedDesc: "مفتوح مدى الحياة — سجل غير محدود، وتصدير، والمزيد.",
      startTrialError: "تعذر بدء التجربة المجانية.",
      checkoutError: "تعذر بدء عملية الدفع.",
      paymentsSecureNoteAndroid: "تتم معالجة المدفوعات بأمان عبر Google Play.",
      paymentsSecureNoteApple: "تتم معالجة المدفوعات بأمان عبر App Store.",
      restorePurchasesBtn: "استعادة المشتريات",
      restoreError: "تعذرت استعادة المشتريات. حاولي مرة أخرى أو تواصلي مع الدعم.",
      features: [
        "وصول كامل لحاسبة الجرعات والمتابعة اليومية",
        "قاعدة بيانات أطعمة قابلة للبحث بالكامل، وسجل غير محدود",
        "تصدير تقرير PDF لطبيبك",
        "رؤى واتجاهات عبر الوجبات وقراءات السكر",
      ],
    },
    forgotPassword: {
      title: "استعادة كلمة المرور",
      description: "أدخلي البريد الإلكتروني المسجل بحسابك وسنرسل لك رابطاً لاستعادة كلمة المرور.",
      emailLabel: "البريد الإلكتروني",
      sendResetLinkBtn: "إرسال رابط الاستعادة",
      sendingBtn: "جارٍ الإرسال…",
      devModeNote: "وضع التطوير (لم يتم إعداد مزوّد بريد إلكتروني) — رابط الاستعادة:",
      backToLogin: "العودة لتسجيل الدخول",
    },
    resetPassword: {
      title: "تعيين كلمة مرور جديدة",
      missingTokenMessage: "هذا الرابط لا يحتوي على رمز الاستعادة. اطلبي رابطاً جديداً من صفحة استعادة كلمة المرور.",
      missingTokenError: "هذا الرابط لا يحتوي على رمز الاستعادة.",
      passwordsDontMatch: "كلمتا المرور غير متطابقتين.",
      passwordUpdatedMessage: "تم تحديث كلمة المرور — جارٍ نقلك إلى لوحتك الرئيسية…",
      newPasswordLabel: "كلمة المرور الجديدة",
      confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
      resetPasswordBtn: "إعادة تعيين كلمة المرور",
      backToLogin: "العودة لتسجيل الدخول",
    },
    privacy: {
      title: "سياسة الخصوصية",
      lastUpdated: "آخر تحديث: 9 أغسطس 2026",
      operatedBy: "يتم تشغيل GlucoDose بواسطة HFarid Apps (\"نحن\").",
      sections: [
        {
          heading: "المعلومات التي نجمعها",
          body: "معلومات الحساب: اسم المستخدم، البريد الإلكتروني (اختياري، يُستخدم فقط لاستعادة كلمة المرور)، وكلمة مرور مُشفّرة بشكل آمن — لا نقوم أبداً بتخزين كلمة مرورك كنص عادي. المعلومات الصحية والشخصية التي تختارين إدخالها: العمر، الجنس، نوع مرض السكري، تاريخ التشخيص، نظام الأنسولين أو الأدوية، ومعامل الكارب / حساسية الأنسولين الخاصين بك. الإدخالات المسجلة: قراءات السكر، عدد الكربوهيدرات، جرعات الأنسولين، وأي ملاحظات تضيفينها، كل منها مع وقت التسجيل. معلومات الدفع: إذا اشتريتِ بريميوم، تتم معالجة الدفع مباشرة عبر Paymob — لا نرى أو نخزّن تفاصيل بطاقتك أبداً، فقط ما إذا كانت عملية الدفع ناجحة.",
        },
        {
          heading: "كيف نستخدم معلوماتك",
          body: "لتوفير ميزات التطبيق الأساسية: حساب الجرعات المقترحة، تتبع سجلك، وعرض اتجاهاتك. لإرسال بريد إلكتروني لاستعادة كلمة المرور إذا طلبتِ ذلك. لمعالجة عملية شراء بريميوم لمرة واحدة. لا نستخدم بياناتك الصحية للإعلانات، ولا نبيع بياناتك لأي شخص.",
        },
        {
          heading: "خدمات الطرف الثالث",
          body: "نستخدم عدداً صغيراً من خدمات الطرف الثالث لتشغيل التطبيق: Paymob لمعالجة المدفوعات، وResend لإرسال الرسائل الإلكترونية التشغيلية (مثل استعادة كلمة المرور)، ومزود استضافة/قاعدة بيانات لتشغيل التطبيق وتخزين بياناتك بأمان. يتلقى كل منها الحد الأدنى فقط من المعلومات اللازمة لأداء مهمته.",
        },
        {
          heading: "الاحتفاظ بالبيانات وحذفها",
          body: "يتم الاحتفاظ ببياناتك طالما أن حسابك موجود. يمكنك حذف حسابك وكل ما فيه بشكل نهائي — الملف الشخصي، الإدخالات المسجلة، والسجل — في أي وقت من الإعدادات داخل التطبيق. هذا الإجراء فوري ولا يمكن التراجع عنه.",
        },
        {
          heading: "أمان البيانات",
          body: "يتم تشفير كلمات المرور باستخدام bcrypt ولا يتم تخزينها أو مقارنتها كنص عادي أبداً. تستخدم الجلسات ملفات تعريف ارتباط (cookies) موقّعة وhttpOnly. جميع الاتصالات بالتطبيق مشفّرة (HTTPS).",
        },
        {
          heading: "إخلاء المسؤولية الطبية",
          body: "GlucoDose هو أداة لإدارة الذات، وليس بديلاً عن الاستشارة الطبية المهنية. حسابات الجرعات هي تقديرات مبنية على معادلات تقومين أنتِ وفريق رعايتك بضبطها — تأكدي دائماً من قرارات الجرعات مع طبيبك أو فريق رعاية السكري.",
        },
        {
          heading: "خصوصية الأطفال",
          body: "يُقصد باستخدام GlucoDose أن يكون من قبل البالغين الذين يديرون رعاية السكري الخاصة بهم، أو من قبل ولي أمر يدير رعاية شخص يعتمد عليه. إذا كنتِ ولي أمر تنشئين حساباً نيابة عن طفل، فأنتِ مسؤولة عن هذا الحساب وتوافقين على هذه السياسة نيابة عنه.",
        },
        {
          heading: "تغييرات على هذه السياسة",
          body: "إذا أجرينا تغييرات جوهرية على هذه السياسة، سنقوم بتحديث تاريخ \"آخر تحديث\" أعلاه. استمرار استخدام التطبيق بعد أي تغيير يعني أنكِ توافقين على السياسة المحدثة.",
        },
        {
          heading: "تواصلي معنا",
          body: "أسئلة حول هذه السياسة أو بياناتك؟ راسلينا على heba@aosama.me.",
        },
      ],
    },
    support: {
      title: "الدعم",
      intro: "تحتاجين مساعدة في GlucoDose؟ يسعدنا الرد على أسئلتك، وإصلاح الأخطاء، وسماع ملاحظاتك.",
      contactHeading: "تواصلي معنا",
      contactBody: "راسلينا على heba@aosama.me وسنرد عليكِ في أقرب وقت ممكن.",
      faqHeading: "الأسئلة الشائعة",
      faq: [
        {
          q: "كيف تعمل الفترة التجريبية المجانية؟",
          a: `يمنحكِ GlucoDose فترة تجريبية مجانية لمدة ${TRIAL_DAYS} أيام عند التسجيل، مع وصول كامل لجميع الميزات. بعد انتهاء الفترة التجريبية، تفتح عملية شراء بريميوم لمرة واحدة (${ONE_TIME_PRICE_DISPLAY}) التطبيق بشكل دائم — بدون اشتراك، وبدون رسوم متكررة.`,
        },
        {
          q: "كيف أستعيد عملية شراء بريميوم الخاصة بي؟",
          a: "افتحي بريميوم من القائمة واضغطي على \"استعادة المشتريات\". يعمل هذا على نفس المنصة (App Store أو Google Play) التي اشتريتِ منها في الأصل.",
        },
        {
          q: "كيف أحذف حسابي أو بياناتي؟",
          a: "اذهبي إلى الإعدادات في التطبيق واضغطي على \"حذف الحساب\". يؤدي هذا إلى إزالة ملفك الشخصي وإدخالاتك المسجلة وسجلك بشكل نهائي، ولا يمكن التراجع عن هذا الإجراء.",
        },
        {
          q: "وجدتُ خطأً أو لدي اقتراح ميزة.",
          a: "راسلينا على heba@aosama.me مع أكبر قدر ممكن من التفاصيل (ماذا كنتِ تفعلين، وماذا توقعتِ، وماذا حدث فعلياً) — لقطات الشاشة تساعد كثيراً.",
        },
      ],
    },
  },
};

export type Lang = keyof typeof STRINGS;

export const DIABETES_TYPE_LABELS: Record<Lang, Record<(typeof DIABETES_TYPE_IDS)[number], string>> = {
  en: { type1: "Type 1", type2: "Type 2", gestational: "Gestational", other: "Other / LADA / MODY" },
  ar: { type1: "النوع الأول", type2: "النوع الثاني", gestational: "سكري الحمل", other: "آخر / LADA / MODY" },
};

export function diabetesTypesFor(lang: Lang) {
  return DIABETES_TYPE_IDS.map((id) => ({ id, label: DIABETES_TYPE_LABELS[lang][id] }));
}
