// Brand/drug names are intentionally left untranslated in both languages —
// packaging and prescriptions use the Latin-script brand name regardless of
// locale, so translating them would hurt usability, not help it.
export const RAPID_INSULINS = [
  "NovoRapid (Aspart)",
  "Apidra (Glulisine)",
  "Humalog (Lispro)",
  "Fiasp",
  "Actrapid (Regular/Short-acting)",
  "Other rapid/short-acting",
];

export const BASAL_INSULINS = [
  "Lantus (Glargine)",
  "Levemir (Detemir)",
  "Tresiba (Degludec)",
  "Toujeo",
  "Basaglar",
  "Insulatard (NPH)",
  "Other basal/long-acting",
];

export const PILL_OPTIONS = [
  "Metformin",
  "Glimepiride",
  "Gliclazide",
  "Sitagliptin",
  "Empagliflozin",
  "Dapagliflozin",
  "Pioglitazone",
  "Repaglinide",
  "Acarbose",
  "Other pill",
];

export const DIABETES_TYPE_IDS = ["type1", "type2", "gestational", "other"] as const;

export const ONE_TIME_PRICE_DISPLAY = "$10";
export const TRIAL_DAYS = 7;

// Full UI-chrome translation (EN/AR), RTL-tested on every screen. Per the
// original design handoff's stated scope, the food database (FOOD_DB) and
// brand/drug names above are out of scope — those are a content-catalog
// translation project, not UI chrome.
export const STRINGS = {
  en: {
    nav: {
      dashboard: "Dashboard",
      setup: "Setup",
      history: "History",
      premium: "Premium",
      tips: "Tips",
      community: "Community",
      share: "Share",
      home: "Home",
      welcomeBack: (name: string) => (name ? `Welcome back, ${name}!` : "Welcome back!"),
      age: (age: number | string) => `Age: ${age}`,
    },
    common: {
      continueBtn: "Continue",
      savingBtn: "Saving…",
      somethingWrong: "Something went wrong.",
      loading: "Loading…",
      dash: "—",
      back: "Back",
    },
    auth: {
      appTagline: "Personalized carb ratio and insulin dose calculator.",
      language: "Language",
      login: "Log in",
      signup: "Sign up",
      usernameLabel: "Username",
      usernamePlaceholder: "e.g. mona_h",
      passwordLabel: "Password",
      emailLabel: "Email",
      emailHint: "Required — lets you reset your password if you forget it",
      emailPlaceholder: "you@example.com",
      fillRequiredFields: "Please fill in all required fields.",
      passwordTooShort: "Password must be at least 8 characters.",
      pleaseWait: "Please wait…",
      forgotPassword: "Forgot password?",
      disclaimer:
        "This app supports diabetes self-management and does not replace medical advice. Always confirm dosing decisions with your care team.",
    },
    onboarding: {
      title: "Set up your profile",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Your name",
      genderLabel: "Gender",
      female: "Female",
      male: "Male",
      ageLabel: "Age",
      agePlaceholder: "e.g. 29",
      unitsLabel: "Preferred glucose units",
      diagnosisDateLabel: "When were you diagnosed?",
      diabetesTypeLabel: "Type of diabetes",
      treatmentModeLabel: "How do you manage your diabetes?",
      insulin: "Insulin",
      pills: "Pills",
      both: "Both",
      insulinRegimenTitle: "Insulin regimen",
      deliveryLabel: "How is your insulin delivered?",
      injections: "Injections (MDI)",
      pump: "Insulin pump",
      pumpInsulinLabel: "Insulin used in pump",
      pumpInsulinHint: "Pumps use rapid-acting insulin only",
      bolusUnitsLabel: "Bolus (meal) units per day",
      bolusUnitsHint: "Optional — from your pump history, total meal/correction boluses in a typical day",
      bolusPlaceholder: "e.g. 40 (optional)",
      basalBackgroundLabel: "Basal (background) units per day",
      basalBackgroundHint: "Total basal delivered by the pump in a typical day",
      basalPumpPlaceholder: "e.g. 20",
      rapidInsulinLabel: "Rapid-acting (mealtime) insulin",
      rapidUnitsLabel: "Total rapid units per day",
      rapidUnitsHint: "Sum of all mealtime doses across a typical day",
      rapidPlaceholder: "e.g. 60",
      basalInsulinLabel: "Basal (long-acting) insulin",
      basalUnitsLabel: "Total basal units per day",
      basalPlaceholder: "e.g. 35",
      oralMedicationTitle: "Oral medication(s)",
      reviewIntro:
        "Based on your total daily insulin dose, here are your calculated ratios (500 rule for carb ratio, 1500 rule for insulin sensitivity):",
      totalDailyDoseLabel: "Total daily dose",
      carbRatioLabel: "Carb ratio",
      sensitivityLabel: "Sensitivity (ISF)",
      reviewSummary: (carbRatio: string, isf: string) =>
        `1 unit of rapid insulin covers about ${carbRatio}g of carbohydrate, and lowers blood glucose by about ${isf} mg/dL.`,
      doctorOverrideLabel: "My doctor gave me different numbers",
      on: "On",
      off: "Off",
      carbRatioManualLabel: "Carb ratio (g per unit)",
      isfManualLabel: "ISF (mg/dL per unit)",
      doctorOverrideRequired: "Enter both values your doctor gave you to continue.",
      pillsOnlyNotice:
        "Since you're managing with oral medication only, dose calculations are skipped — you can still log meals and glucose readings for your history.",
      finishSetup: "Finish setup",
      saveError: "Could not save your profile.",
    },
    dashboard: {
      overviewTab: "Overview",
      calculatorTab: "Calculator",
      logYourDayTitle: "Log Your Day",
      timeInRangeLabel: "Today's Time in Range",
      green: "Green",
      fair: "Fair",
      needsAttention: "Needs attention",
      noData: "No data",
      streakLabel: "Day Streak",
      pointsLabel: "Action Points",
      quickLogTitle: "Quick Log",
      logBGBtn: "+ Log BG",
      currentBGLabel: "Current BG",
      insulinTakenLabel: "Insulin Taken",
      yourHistoryTitle: "Your History",
      viewAllBtn: "View all",
      nothingLoggedYet: "Nothing logged yet.",
      unlockPremiumTitle: "Unlock Premium",
      unlockPremiumDesc: "Unlimited history, PDF reports, CGM sync.",
      subscribeBtn: "Subscribe",
      bgBadge: (v: number | string) => `BG ${v}`,
      carbsBadge: (v: number | string) => `Carbs ${v}g`,
      insulinBadge: (v: number | string) => `Insulin ${v}u`,
    },
    calculator: {
      noInsulinTitle: "No insulin dosing on file",
      noInsulinDesc: "You can still log carbs and glucose. Add insulin info in Setup to unlock dose calculations.",
      mealTab: "Meal",
      mealCorrTab: "Meal+Corr.",
      correctionTab: "Correction only",
      hypoTab: "Low BG (hypo)",
      mealItemsTitle: "Meal items",
      noItemsYet: "No items added yet.",
      addFoodFromList: "+ Add food from list",
      addYourOwnFood: "+ Add your own food",
      totalCarbsLabel: "Total carbs",
      currentBGLabel: (unit: string) => `Current BG (${unit})`,
      currentBGOptionalHint: "Optional — just for your records",
      targetBGLabel: (unit: string) => `Target BG (${unit})`,
      mealDoseLabel: "Meal dose",
      mealCorrDoseLabel: "Meal + correction dose",
      correctionDoseLabel: "Correction dose",
      hypoCarbsLabel: "Carbs needed (low BG)",
      treatLowFirst: "Treat the low first — recheck BG in 15 minutes.",
      units: "units",
      gCarbs: "g carbs",
      logThisBtn: "Log this",
      savedBtn: "Saved ✓",
      addAFoodTitle: "Add a food",
      searchPlaceholder: "Search food… e.g. rice, banana",
      allCategory: "All",
      noFoodsFound: "No foods found.",
      mineTag: "mine",
      addYourOwnFoodTitle: "Add your own food",
      foodNameLabel: "Food name",
      foodNamePlaceholder: "e.g. Mom's stuffed cabbage",
      portionLabel: "Portion size",
      portionPlaceholder: "e.g. 1 roll (80g)",
      carbsPerPortionLabel: "Carbs (g) per portion",
      carbsPlaceholder: "e.g. 18",
      addToMyFoods: "Add to my foods",
      carbsUnit: (g: number | string) => `${g}g carbs`,
      mealCorrSummary: (meal: string, corr: string) => `Meal ${meal}u + correction ${corr}u`,
      myFoodsCategory: "My Foods",
      onePortionFallback: "1 portion",
      gramsShort: (g: number | string) => `${g}g`,
    },
    history: {
      timeInRangeTitle: "Time in range",
      noReadingsPeriod: "No glucose readings logged in this period yet.",
      low: "Low",
      inRange: "In range",
      high: "High",
      logBGReadingBtn: "+ Log BG reading",
      filterAll: "All",
      filterMeals: "Meals",
      filterDoses: "Doses",
      filterGlucose: "Glucose",
      nothingLoggedMessage: "Nothing logged yet. Doses and readings you log from the Calculator will show up here.",
      hiddenEntries: (n: number) => `${n} more entries hidden`,
      freeAccountsMessage: "Free accounts see your last 15 entries. Go Premium for unlimited history and export.",
      seePremiumBtn: "See Premium",
      logGlucoseTitle: "Log a glucose reading",
      bloodGlucoseLabel: (unit: string) => `Blood glucose (${unit})`,
      saveReadingBtn: "Save reading",
      mealDoseType: "Meal dose",
      mealCorrType: "Meal + correction",
      correctionType: "Correction dose",
      hypoType: "Low BG treated",
      bgType: "Glucose reading",
      today: "Today",
      targetArrow: (v: number | string) => ` → target ${v}`,
      bgReading: (v: number | string) => `BG ${v}`,
    },
    tips: {
      title: "Tips for you",
      subtitle: "Based on what you've logged recently.",
      emptyTitle: "Not enough data yet",
      emptyDesc: "Log a few more meals and glucose readings and we'll surface personalized tips here.",
      timeInRangeHighTip: (pct: number) =>
        `Your readings have been high ${pct}% of the time over the last 14 days — worth reviewing your correction doses with your care team.`,
      timeInRangeLowTip: (pct: number) =>
        `Your readings have been low ${pct}% of the time over the last 14 days — talk to your care team about your ISF or carb ratio.`,
      timeOfDayTip: (window: string, pct: number) => `Your BG tends to run high after ${window} (${pct}% of readings in that window).`,
      loggingGapTip: "You haven't logged anything in a couple of days — log a reading to keep your streak going.",
      windowBreakfast: "breakfast",
      windowLunch: "lunch",
      windowDinner: "dinner",
      windowOther: "other times",
    },
    community: {
      title: "Community",
      subtitle: "See what other GlucoDose users are sharing.",
      emptyTitle: "No posts yet",
      emptyDesc: "Be the first to share something with the community.",
      newPostBtn: "+ New post",
      composeTitle: "Share with the community",
      composePlaceholder: "Share a tip, a win, or a question…",
      postBtn: "Post",
      postError: "Could not post. Please try again.",
      justNow: "Just now",
      minutesAgo: (n: number) => `${n}m ago`,
      hoursAgo: (n: number) => `${n}h ago`,
      daysAgo: (n: number) => `${n}d ago`,
    },
    share: {
      title: "Share your progress",
      subtitle: "Send your stats to a friend or your care team.",
      streakLine: (n: number) => `🔥 ${n}-day streak`,
      pointsLine: (n: number) => `⭐ ${n} action points`,
      timeInRangeLine: (pct: number) => `🎯 ${pct}% time in range (last 14 days)`,
      shareBtn: "Share",
      copiedMsg: "Copied to clipboard!",
    },
    setup: {
      setupRatiosTitle: "Setup & Ratios",
      premiumBadge: "Premium",
      freeBadge: "Free",
      usernameLabel: "Username",
      emailLabel: "Email",
      addEmailBtn: "+ Add email",
      genderLabel: "Gender",
      ageLabel: "Age",
      dateDiagnosedLabel: "Date diagnosed",
      diabetesTypeLabel: "Diabetes type",
      glucoseUnitsLabel: "Glucose units",
      treatmentLabel: "Treatment",
      deliveryLabel: "Delivery",
      pillsLabel: "Pills",
      autoRatiosTitle: "Auto-Ratios",
      carbRatioTDDLabel: "Carb ratio (TDD)",
      insulinSensitivityLabel: "Insulin sensitivity",
      recalculateBtn: "Recalculate",
      doctorValuesNote: "Using your doctor's custom values.",
      unlockPremiumTitle: "Unlock Premium",
      unlockPremiumDesc: "Unlimited history, PDF reports, CGM sync.",
      subscribeBtn: "Subscribe",
      editTreatmentBtn: "Edit treatment info",
      logoutBtn: "Log out",
      emailModalTitle: "Email for password reset",
      emailModalHint: "Used only to send you a password-reset link if you forget your password.",
      saveEmailBtn: "Save email",
      emailSaveError: "Could not save email.",
    },
    premium: {
      title: "GlucoDose Premium",
      subtitle: "Everything you need to manage diabetes with confidence.",
      trialActive: (days: number) => `Free trial active — ${days} day${days === 1 ? "" : "s"} left`,
      trialSubtitle: "Subscribe below to keep Premium after your trial ends.",
      trialEnded: "Your free trial has ended",
      paymentReceived: "Payment received — confirming…",
      checkoutCancelled: "Checkout cancelled",
      onetimePurchaseLabel: "One-time purchase",
      payOnceMessage: "Pay once, keep Premium forever",
      startTrialBtn: (days: number) => `Start ${days}-day free trial`,
      unlockPremiumBtn: "Unlock Premium",
      paymentsSecureNote: "Payments are processed securely by Paymob.",
      premiumUnlockedTitle: "You're Premium",
      premiumUnlockedDesc: "Unlocked for life — unlimited history, export, and more.",
      startTrialError: "Could not start trial.",
      checkoutError: "Could not start checkout.",
      features: [
        "Full searchable food database, unlimited history",
        "Export history as CSV for your doctor",
        "Trend insights across meals & glucose readings",
        "Multiple insulin/pill regimen profiles",
      ],
    },
    forgotPassword: {
      title: "Reset your password",
      description: "Enter the email on your account and we'll send you a link to reset your password.",
      emailLabel: "Email",
      sendResetLinkBtn: "Send reset link",
      sendingBtn: "Sending…",
      devModeNote: "Dev mode (no email provider configured) — reset link:",
      backToLogin: "Back to log in",
    },
    resetPassword: {
      title: "Set a new password",
      missingTokenMessage: "This link is missing its reset token. Request a new one from the forgot password page.",
      missingTokenError: "This reset link is missing its token.",
      passwordsDontMatch: "Passwords don't match.",
      passwordUpdatedMessage: "Password updated — taking you to your dashboard…",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm new password",
      resetPasswordBtn: "Reset password",
      backToLogin: "Back to log in",
    },
  },
  ar: {
    nav: {
      dashboard: "الرئيسية",
      setup: "الإعدادات",
      history: "السجل",
      premium: "بريميوم",
      tips: "نصائح",
      community: "المجتمع",
      share: "مشاركة",
      home: "الرئيسية",
      welcomeBack: (name: string) => (name ? `أهلاً بعودتك، ${name}!` : "أهلاً بعودتك!"),
      age: (age: number | string) => `العمر: ${age}`,
    },
    common: {
      continueBtn: "متابعة",
      savingBtn: "جارٍ الحفظ…",
      somethingWrong: "حدث خطأ ما.",
      loading: "جارٍ التحميل…",
      dash: "—",
      back: "رجوع",
    },
    auth: {
      appTagline: "حاسبة معامل الكارب وحساسية الأنسولين الخاصة بك.",
      language: "اللغة",
      login: "تسجيل الدخول",
      signup: "حساب جديد",
      usernameLabel: "اسم المستخدم",
      usernamePlaceholder: "مثال: mona_h",
      passwordLabel: "كلمة المرور",
      emailLabel: "البريد الإلكتروني",
      emailHint: "إلزامي — يتيح لك استعادة كلمة المرور إذا نسيتها",
      emailPlaceholder: "you@example.com",
      fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة.",
      passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
      pleaseWait: "يرجى الانتظار…",
      forgotPassword: "نسيت كلمة المرور؟",
      disclaimer:
        "يساعدك هذا التطبيق على إدارة مرض السكري بنفسك، ولا يغني عن الاستشارة الطبية. تأكدي دائماً من قرارات الجرعات مع فريقك الطبي.",
    },
    onboarding: {
      title: "أنشئي ملفك الشخصي",
      fullNameLabel: "الاسم الكامل",
      fullNamePlaceholder: "اسمك",
      genderLabel: "الجنس",
      female: "أنثى",
      male: "ذكر",
      ageLabel: "العمر",
      agePlaceholder: "مثال: 29",
      unitsLabel: "وحدة قياس السكر المفضلة",
      diagnosisDateLabel: "متى تم تشخيصك؟",
      diabetesTypeLabel: "نوع مرض السكري",
      treatmentModeLabel: "كيف تديرين مرض السكري؟",
      insulin: "أنسولين",
      pills: "حبوب",
      both: "كلاهما",
      insulinRegimenTitle: "نظام الأنسولين",
      deliveryLabel: "كيف يُعطى الأنسولين؟",
      injections: "حقن (متعددة الجرعات)",
      pump: "مضخة أنسولين",
      pumpInsulinLabel: "الأنسولين المستخدم في المضخة",
      pumpInsulinHint: "تستخدم المضخات الأنسولين سريع المفعول فقط",
      bolusUnitsLabel: "وحدات الوجبة (بولس) يومياً",
      bolusUnitsHint: "اختياري — من سجل مضختك، إجمالي جرعات الوجبات والتصحيح في يوم معتاد",
      bolusPlaceholder: "مثال: 40 (اختياري)",
      basalBackgroundLabel: "الوحدات الأساسية يومياً",
      basalBackgroundHint: "إجمالي الجرعة الأساسية التي تعطيها المضخة في يوم معتاد",
      basalPumpPlaceholder: "مثال: 20",
      rapidInsulinLabel: "الأنسولين سريع المفعول (وقت الوجبات)",
      rapidUnitsLabel: "إجمالي الوحدات سريعة المفعول يومياً",
      rapidUnitsHint: "مجموع جرعات الوجبات في يوم معتاد",
      rapidPlaceholder: "مثال: 60",
      basalInsulinLabel: "الأنسولين طويل المفعول (الأساسي)",
      basalUnitsLabel: "إجمالي الوحدات الأساسية يومياً",
      basalPlaceholder: "مثال: 35",
      oralMedicationTitle: "الأدوية عن طريق الفم",
      reviewIntro:
        "بناءً على إجمالي جرعة الأنسولين اليومية، إليك النسب المحسوبة (قاعدة 500 لمعامل الكارب، وقاعدة 1500 لحساسية الأنسولين):",
      totalDailyDoseLabel: "إجمالي الجرعة اليومية",
      carbRatioLabel: "معامل الكارب",
      sensitivityLabel: "الحساسية (ISF)",
      reviewSummary: (carbRatio: string, isf: string) =>
        `تغطي كل وحدة أنسولين سريع حوالي ${carbRatio} جم من الكربوهيدرات، وتخفض سكر الدم بحوالي ${isf} ملغ/دل.`,
      doctorOverrideLabel: "طبيبي أعطاني أرقاماً مختلفة",
      on: "مفعّل",
      off: "متوقف",
      carbRatioManualLabel: "معامل الكارب (جم لكل وحدة)",
      isfManualLabel: "ISF (ملغ/دل لكل وحدة)",
      doctorOverrideRequired: "أدخلي كلا القيمتين اللتين أعطاك إياهما طبيبك للمتابعة.",
      pillsOnlyNotice:
        "بما أنك تدارين حالتك بالأدوية الفموية فقط، يتم تخطي حسابات الجرعات — يمكنك مع ذلك تسجيل الوجبات وقراءات السكر في سجلك.",
      finishSetup: "إنهاء الإعداد",
      saveError: "تعذر حفظ ملفك الشخصي.",
    },
    dashboard: {
      overviewTab: "نظرة عامة",
      calculatorTab: "الحاسبة",
      logYourDayTitle: "سجّلي يومك",
      timeInRangeLabel: "الوقت ضمن النطاق اليوم",
      green: "جيد",
      fair: "متوسط",
      needsAttention: "يحتاج انتباه",
      noData: "لا توجد بيانات",
      streakLabel: "أيام متتالية",
      pointsLabel: "نقاط النشاط",
      quickLogTitle: "تسجيل سريع",
      logBGBtn: "+ تسجيل السكر",
      currentBGLabel: "السكر الحالي",
      insulinTakenLabel: "الأنسولين المأخوذ",
      yourHistoryTitle: "سجلك",
      viewAllBtn: "عرض الكل",
      nothingLoggedYet: "لم يتم تسجيل أي شيء بعد.",
      unlockPremiumTitle: "افتحي بريميوم",
      unlockPremiumDesc: "سجل غير محدود، تقارير PDF، ومزامنة أجهزة قياس السكر المستمر.",
      subscribeBtn: "اشتراك",
      bgBadge: (v: number | string) => `السكر ${v}`,
      carbsBadge: (v: number | string) => `كارب ${v}جم`,
      insulinBadge: (v: number | string) => `أنسولين ${v}و`,
    },
    calculator: {
      noInsulinTitle: "لا يوجد نظام أنسولين مسجل",
      noInsulinDesc: "لا يزال بإمكانك تسجيل الكارب والسكر. أضيفي بيانات الأنسولين في الإعدادات لتفعيل حساب الجرعات.",
      mealTab: "وجبة",
      mealCorrTab: "وجبة+تصحيح",
      correctionTab: "تصحيح فقط",
      hypoTab: "انخفاض السكر",
      mealItemsTitle: "عناصر الوجبة",
      noItemsYet: "لم تتم إضافة عناصر بعد.",
      addFoodFromList: "+ إضافة طعام من القائمة",
      addYourOwnFood: "+ إضافة طعامك الخاص",
      totalCarbsLabel: "إجمالي الكارب",
      currentBGLabel: (unit: string) => `السكر الحالي (${unit})`,
      currentBGOptionalHint: "اختياري — لسجلاتك فقط",
      targetBGLabel: (unit: string) => `السكر المستهدف (${unit})`,
      mealDoseLabel: "جرعة الوجبة",
      mealCorrDoseLabel: "جرعة الوجبة + التصحيح",
      correctionDoseLabel: "جرعة التصحيح",
      hypoCarbsLabel: "الكارب المطلوب (انخفاض السكر)",
      treatLowFirst: "عالجي الانخفاض أولاً — أعيدي فحص السكر بعد 15 دقيقة.",
      units: "وحدة",
      gCarbs: "جم كارب",
      logThisBtn: "تسجيل",
      savedBtn: "تم الحفظ ✓",
      addAFoodTitle: "إضافة طعام",
      searchPlaceholder: "ابحثي عن طعام… مثال: أرز، موز",
      allCategory: "الكل",
      noFoodsFound: "لا توجد أطعمة مطابقة.",
      mineTag: "خاصتي",
      addYourOwnFoodTitle: "إضافة طعامك الخاص",
      foodNameLabel: "اسم الطعام",
      foodNamePlaceholder: "مثال: محشي أمي",
      portionLabel: "حجم الحصة",
      portionPlaceholder: "مثال: قطعة واحدة (80جم)",
      carbsPerPortionLabel: "الكارب (جم) لكل حصة",
      carbsPlaceholder: "مثال: 18",
      addToMyFoods: "إضافة إلى أطعمتي",
      carbsUnit: (g: number | string) => `${g}جم كارب`,
      mealCorrSummary: (meal: string, corr: string) => `وجبة ${meal}و + تصحيح ${corr}و`,
      myFoodsCategory: "أطعمتي",
      onePortionFallback: "حصة واحدة",
      gramsShort: (g: number | string) => `${g}جم`,
    },
    history: {
      timeInRangeTitle: "الوقت ضمن النطاق",
      noReadingsPeriod: "لا توجد قراءات سكر مسجلة في هذه الفترة بعد.",
      low: "منخفض",
      inRange: "ضمن النطاق",
      high: "مرتفع",
      logBGReadingBtn: "+ تسجيل قراءة سكر",
      filterAll: "الكل",
      filterMeals: "الوجبات",
      filterDoses: "الجرعات",
      filterGlucose: "السكر",
      nothingLoggedMessage: "لم يتم تسجيل أي شيء بعد. الجرعات والقراءات التي تسجلينها من الحاسبة ستظهر هنا.",
      hiddenEntries: (n: number) => `${n} إدخالات إضافية مخفية`,
      freeAccountsMessage: "تعرض الحسابات المجانية آخر 15 إدخالاً فقط. اشتركي في بريميوم للسجل غير المحدود والتصدير.",
      seePremiumBtn: "عرض بريميوم",
      logGlucoseTitle: "تسجيل قراءة سكر",
      bloodGlucoseLabel: (unit: string) => `سكر الدم (${unit})`,
      saveReadingBtn: "حفظ القراءة",
      mealDoseType: "جرعة وجبة",
      mealCorrType: "وجبة + تصحيح",
      correctionType: "جرعة تصحيح",
      hypoType: "تم علاج انخفاض السكر",
      bgType: "قراءة سكر",
      today: "اليوم",
      targetArrow: (v: number | string) => ` ← الهدف ${v}`,
      bgReading: (v: number | string) => `السكر ${v}`,
    },
    tips: {
      title: "نصائح لك",
      subtitle: "بناءً على ما سجّلتِه مؤخراً.",
      emptyTitle: "لا توجد بيانات كافية بعد",
      emptyDesc: "سجّلي المزيد من الوجبات وقراءات السكر وستظهر لكِ نصائح مخصصة هنا.",
      timeInRangeHighTip: (pct: number) =>
        `كانت قراءاتك مرتفعة ${pct}% من الوقت خلال آخر 14 يوماً — يستحق مراجعة جرعات التصحيح مع فريق الرعاية.`,
      timeInRangeLowTip: (pct: number) =>
        `كانت قراءاتك منخفضة ${pct}% من الوقت خلال آخر 14 يوماً — تحدثي مع فريق الرعاية عن حساسية الأنسولين أو معامل الكارب.`,
      timeOfDayTip: (window: string, pct: number) => `يميل سكر الدم للارتفاع بعد ${window} (${pct}% من القراءات في هذه الفترة).`,
      loggingGapTip: "لم تسجّلي شيئاً منذ يومين — سجّلي قراءة للحفاظ على تتابعك.",
      windowBreakfast: "الإفطار",
      windowLunch: "الغداء",
      windowDinner: "العشاء",
      windowOther: "أوقات أخرى",
    },
    community: {
      title: "المجتمع",
      subtitle: "شاهدي ما يشاركه مستخدمو GlucoDose الآخرون.",
      emptyTitle: "لا توجد منشورات بعد",
      emptyDesc: "كوني أول من يشارك شيئاً مع المجتمع.",
      newPostBtn: "+ منشور جديد",
      composeTitle: "شاركي مع المجتمع",
      composePlaceholder: "شاركي نصيحة، إنجازاً، أو سؤالاً…",
      postBtn: "نشر",
      postError: "تعذر النشر. حاولي مرة أخرى.",
      justNow: "الآن",
      minutesAgo: (n: number) => `منذ ${n} د`,
      hoursAgo: (n: number) => `منذ ${n} س`,
      daysAgo: (n: number) => `منذ ${n} يوم`,
    },
    share: {
      title: "شاركي تقدمك",
      subtitle: "أرسلي إحصائياتك لصديقة أو فريق الرعاية.",
      streakLine: (n: number) => `🔥 ${n} يوماً متتالياً`,
      pointsLine: (n: number) => `⭐ ${n} نقطة نشاط`,
      timeInRangeLine: (pct: number) => `🎯 ${pct}% ضمن النطاق (آخر 14 يوماً)`,
      shareBtn: "مشاركة",
      copiedMsg: "تم النسخ إلى الحافظة!",
    },
    setup: {
      setupRatiosTitle: "الإعدادات والنسب",
      premiumBadge: "بريميوم",
      freeBadge: "مجاني",
      usernameLabel: "اسم المستخدم",
      emailLabel: "البريد الإلكتروني",
      addEmailBtn: "+ إضافة بريد إلكتروني",
      genderLabel: "الجنس",
      ageLabel: "العمر",
      dateDiagnosedLabel: "تاريخ التشخيص",
      diabetesTypeLabel: "نوع مرض السكري",
      glucoseUnitsLabel: "وحدة قياس السكر",
      treatmentLabel: "العلاج",
      deliveryLabel: "طريقة الإعطاء",
      pillsLabel: "الحبوب",
      autoRatiosTitle: "النسب التلقائية",
      carbRatioTDDLabel: "معامل الكارب (TDD)",
      insulinSensitivityLabel: "حساسية الأنسولين",
      recalculateBtn: "إعادة الحساب",
      doctorValuesNote: "يتم استخدام القيم الخاصة بطبيبك.",
      unlockPremiumTitle: "افتحي بريميوم",
      unlockPremiumDesc: "سجل غير محدود، تقارير PDF، ومزامنة أجهزة قياس السكر المستمر.",
      subscribeBtn: "اشتراك",
      editTreatmentBtn: "تعديل بيانات العلاج",
      logoutBtn: "تسجيل الخروج",
      emailModalTitle: "البريد الإلكتروني لاستعادة كلمة المرور",
      emailModalHint: "يُستخدم فقط لإرسال رابط استعادة كلمة المرور إذا نسيتها.",
      saveEmailBtn: "حفظ البريد الإلكتروني",
      emailSaveError: "تعذر حفظ البريد الإلكتروني.",
    },
    premium: {
      title: "بريميوم GlucoDose",
      subtitle: "كل ما تحتاجينه لإدارة مرض السكري بثقة.",
      trialActive: (days: number) => `التجربة المجانية مفعّلة — تبقى ${days} ${days === 1 ? "يوم" : "أيام"}`,
      trialSubtitle: "اشتركي أدناه للاحتفاظ ببريميوم بعد انتهاء تجربتك.",
      trialEnded: "انتهت تجربتك المجانية",
      paymentReceived: "تم استلام الدفعة — جارٍ التأكيد…",
      checkoutCancelled: "تم إلغاء الدفع",
      onetimePurchaseLabel: "دفعة لمرة واحدة",
      payOnceMessage: "ادفعي مرة واحدة، واحتفظي ببريميوم للأبد",
      startTrialBtn: (days: number) => `ابدئي تجربة ${days} أيام مجانية`,
      unlockPremiumBtn: "افتحي بريميوم",
      paymentsSecureNote: "تتم معالجة المدفوعات بأمان عبر Paymob.",
      premiumUnlockedTitle: "أنتِ عضوة بريميوم",
      premiumUnlockedDesc: "مفتوح مدى الحياة — سجل غير محدود، وتصدير، والمزيد.",
      startTrialError: "تعذر بدء التجربة المجانية.",
      checkoutError: "تعذر بدء عملية الدفع.",
      features: [
        "قاعدة بيانات أطعمة قابلة للبحث بالكامل، وسجل غير محدود",
        "تصدير السجل كملف CSV لطبيبك",
        "رؤى واتجاهات عبر الوجبات وقراءات السكر",
        "ملفات متعددة لأنظمة الأنسولين أو الحبوب",
      ],
    },
    forgotPassword: {
      title: "استعادة كلمة المرور",
      description: "أدخلي البريد الإلكتروني المسجل بحسابك وسنرسل لك رابطاً لاستعادة كلمة المرور.",
      emailLabel: "البريد الإلكتروني",
      sendResetLinkBtn: "إرسال رابط الاستعادة",
      sendingBtn: "جارٍ الإرسال…",
      devModeNote: "وضع التطوير (لم يتم إعداد مزوّد بريد إلكتروني) — رابط الاستعادة:",
      backToLogin: "العودة لتسجيل الدخول",
    },
    resetPassword: {
      title: "تعيين كلمة مرور جديدة",
      missingTokenMessage: "هذا الرابط لا يحتوي على رمز الاستعادة. اطلبي رابطاً جديداً من صفحة استعادة كلمة المرور.",
      missingTokenError: "هذا الرابط لا يحتوي على رمز الاستعادة.",
      passwordsDontMatch: "كلمتا المرور غير متطابقتين.",
      passwordUpdatedMessage: "تم تحديث كلمة المرور — جارٍ نقلك إلى لوحتك الرئيسية…",
      newPasswordLabel: "كلمة المرور الجديدة",
      confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
      resetPasswordBtn: "إعادة تعيين كلمة المرور",
      backToLogin: "العودة لتسجيل الدخول",
    },
  },
};

export type Lang = keyof typeof STRINGS;

export const DIABETES_TYPE_LABELS: Record<Lang, Record<(typeof DIABETES_TYPE_IDS)[number], string>> = {
  en: { type1: "Type 1", type2: "Type 2", gestational: "Gestational", other: "Other / LADA / MODY" },
  ar: { type1: "النوع الأول", type2: "النوع الثاني", gestational: "سكري الحمل", other: "آخر / LADA / MODY" },
};

export function diabetesTypesFor(lang: Lang) {
  return DIABETES_TYPE_IDS.map((id) => ({ id, label: DIABETES_TYPE_LABELS[lang][id] }));
}
