export type Food = {
  name: string;
  category: string;
  portion: string;
  carbs: number;
};

// Food database — name, category, portion label, carbs (g) per that portion.
// Ported verbatim from design_handoff_glucodose/data.js (window.FOOD_DB).
export const FOOD_DB: Food[] = [
  // Grains & Bread
  { name: "White rice, cooked", category: "Grains & Bread", portion: "1 cup (158g)", carbs: 45 },
  { name: "Brown rice, cooked", category: "Grains & Bread", portion: "1 cup (195g)", carbs: 45 },
  { name: "Koshari (rice, lentils, pasta)", category: "Grains & Bread", portion: "1 plate (300g)", carbs: 78 },
  { name: "Pita bread (white)", category: "Grains & Bread", portion: "1 piece (60g)", carbs: 33 },
  { name: "Pita bread (whole wheat)", category: "Grains & Bread", portion: "1 piece (60g)", carbs: 28 },
  { name: "Baguette", category: "Grains & Bread", portion: "1 slice (30g)", carbs: 15 },
  { name: "White sandwich bread", category: "Grains & Bread", portion: "1 slice (28g)", carbs: 14 },
  { name: "Whole wheat bread", category: "Grains & Bread", portion: "1 slice (28g)", carbs: 12 },
  { name: "Spaghetti, cooked", category: "Grains & Bread", portion: "1 cup (140g)", carbs: 43 },
  { name: "Macaroni & cheese", category: "Grains & Bread", portion: "1 cup (200g)", carbs: 40 },
  { name: "Couscous, cooked", category: "Grains & Bread", portion: "1 cup (157g)", carbs: 36 },
  { name: "Freekeh, cooked", category: "Grains & Bread", portion: "1 cup (170g)", carbs: 40 },
  { name: "Oatmeal, cooked", category: "Grains & Bread", portion: "1 cup (234g)", carbs: 27 },
  { name: "Corn flakes", category: "Grains & Bread", portion: "1 cup (28g)", carbs: 24 },
  { name: "Pancake", category: "Grains & Bread", portion: "1 medium (60g)", carbs: 22 },
  { name: "Waffle", category: "Grains & Bread", portion: "1 medium (75g)", carbs: 25 },
  { name: "Croissant", category: "Grains & Bread", portion: "1 medium (57g)", carbs: 26 },
  { name: "Bagel, plain", category: "Grains & Bread", portion: "1 medium (89g)", carbs: 48 },
  { name: "Tortilla, flour", category: "Grains & Bread", portion: "1 medium (45g)", carbs: 24 },
  { name: "Crackers, saltine", category: "Grains & Bread", portion: "5 crackers (15g)", carbs: 10 },

  // Legumes
  { name: "Ful medames (fava beans)", category: "Legumes", portion: "1 cup (170g)", carbs: 32 },
  { name: "Lentil soup", category: "Legumes", portion: "1 cup (240g)", carbs: 20 },
  { name: "Chickpeas, cooked", category: "Legumes", portion: "1 cup (164g)", carbs: 45 },
  { name: "Hummus", category: "Legumes", portion: "1/4 cup (60g)", carbs: 8 },
  { name: "Falafel", category: "Legumes", portion: "3 pieces (75g)", carbs: 18 },
  { name: "Black beans, cooked", category: "Legumes", portion: "1 cup (172g)", carbs: 41 },
  { name: "Red kidney beans, cooked", category: "Legumes", portion: "1 cup (177g)", carbs: 40 },
  { name: "Green peas, cooked", category: "Legumes", portion: "1 cup (160g)", carbs: 25 },

  // Vegetables
  { name: "Mixed vegetable stew (with meat)", category: "Vegetables", portion: "1 plate (250g)", carbs: 15 },
  { name: "Mahshi (stuffed vegetables)", category: "Vegetables", portion: "2 pieces (200g)", carbs: 22 },
  { name: "Potato, boiled", category: "Vegetables", portion: "1 medium (150g)", carbs: 30 },
  { name: "French fries", category: "Vegetables", portion: "1 medium serving (117g)", carbs: 43 },
  { name: "Sweet potato, baked", category: "Vegetables", portion: "1 medium (130g)", carbs: 24 },
  { name: "Corn, boiled", category: "Vegetables", portion: "1 ear (90g)", carbs: 19 },
  { name: "Carrots, cooked", category: "Vegetables", portion: "1 cup (156g)", carbs: 12 },
  { name: "Tomato salad", category: "Vegetables", portion: "1 cup (180g)", carbs: 7 },
  { name: "Green salad (leafy, mixed)", category: "Vegetables", portion: "1 bowl (100g)", carbs: 4 },
  { name: "Okra stew (bamya)", category: "Vegetables", portion: "1 cup (200g)", carbs: 10 },
  { name: "Molokhia", category: "Vegetables", portion: "1 cup (200g)", carbs: 8 },
  { name: "Onion, raw", category: "Vegetables", portion: "1/2 cup chopped (58g)", carbs: 6 },

  // Fruits
  { name: "Apple", category: "Fruits", portion: "1 medium (182g)", carbs: 25 },
  { name: "Banana", category: "Fruits", portion: "1 medium (118g)", carbs: 27 },
  { name: "Orange", category: "Fruits", portion: "1 medium (131g)", carbs: 15 },
  { name: "Mango", category: "Fruits", portion: "1 cup sliced (165g)", carbs: 25 },
  { name: "Grapes", category: "Fruits", portion: "1 cup (92g)", carbs: 16 },
  { name: "Watermelon", category: "Fruits", portion: "1 cup diced (152g)", carbs: 11 },
  { name: "Dates", category: "Fruits", portion: "3 dates (24g)", carbs: 18 },
  { name: "Strawberries", category: "Fruits", portion: "1 cup (152g)", carbs: 11 },
  { name: "Pineapple", category: "Fruits", portion: "1 cup (165g)", carbs: 22 },
  { name: "Guava", category: "Fruits", portion: "1 medium (55g)", carbs: 8 },
  { name: "Fig, dried", category: "Fruits", portion: "2 figs (38g)", carbs: 24 },
  { name: "Raisins", category: "Fruits", portion: "1/4 cup (36g)", carbs: 29 },
  { name: "Pear", category: "Fruits", portion: "1 medium (178g)", carbs: 27 },
  { name: "Peach", category: "Fruits", portion: "1 medium (150g)", carbs: 14 },

  // Dairy
  { name: "Milk, whole", category: "Dairy", portion: "1 cup (244g)", carbs: 12 },
  { name: "Milk, skim", category: "Dairy", portion: "1 cup (245g)", carbs: 12 },
  { name: "Yogurt, plain", category: "Dairy", portion: "1 cup (245g)", carbs: 17 },
  { name: "Yogurt, flavored", category: "Dairy", portion: "1 cup (245g)", carbs: 32 },
  { name: "Rice pudding (roz bel laban)", category: "Dairy", portion: "1 bowl (150g)", carbs: 30 },
  { name: "Ice cream", category: "Dairy", portion: "1/2 cup (66g)", carbs: 16 },
  { name: "Cheese, white (feta-style)", category: "Dairy", portion: "1 oz (28g)", carbs: 1 },
  { name: "Cream cheese", category: "Dairy", portion: "1 tbsp (15g)", carbs: 1 },
  { name: "Labneh", category: "Dairy", portion: "1/4 cup (60g)", carbs: 3 },

  // Meat, poultry, fish (low-carb, included for meal completeness)
  { name: "Grilled chicken breast", category: "Meat & Fish", portion: "100g", carbs: 0 },
  { name: "Kofta (grilled)", category: "Meat & Fish", portion: "3 pieces (150g)", carbs: 3 },
  { name: "Beef steak", category: "Meat & Fish", portion: "100g", carbs: 0 },
  { name: "Fried fish", category: "Meat & Fish", portion: "1 fillet (120g)", carbs: 8 },
  { name: "Grilled shrimp", category: "Meat & Fish", portion: "100g", carbs: 1 },
  { name: "Egg, boiled", category: "Meat & Fish", portion: "1 large", carbs: 1 },
  { name: "Sausage/hot dog", category: "Meat & Fish", portion: "1 link (50g)", carbs: 2 },

  // Fast food & mixed dishes
  { name: "Shawarma sandwich", category: "Fast Food", portion: "1 sandwich (250g)", carbs: 40 },
  { name: "Beef burger with bun", category: "Fast Food", portion: "1 burger (220g)", carbs: 35 },
  { name: "Cheese pizza", category: "Fast Food", portion: "1 slice (107g)", carbs: 30 },
  { name: "Chicken shawarma plate", category: "Fast Food", portion: "1 plate (350g)", carbs: 55 },
  { name: "Fried chicken (2 pieces)", category: "Fast Food", portion: "2 pieces (180g)", carbs: 18 },
  { name: "Hawawshi", category: "Fast Food", portion: "1 piece (200g)", carbs: 38 },
  { name: "Feteer meshaltet (sweet)", category: "Fast Food", portion: "1 slice (150g)", carbs: 55 },
  { name: "Kabsa (rice & meat)", category: "Fast Food", portion: "1 plate (350g)", carbs: 70 },
  { name: "Fattah", category: "Fast Food", portion: "1 plate (300g)", carbs: 60 },

  // Snacks & Sweets
  { name: "Baklava", category: "Snacks & Sweets", portion: "1 piece (40g)", carbs: 22 },
  { name: "Basbousa", category: "Snacks & Sweets", portion: "1 piece (60g)", carbs: 35 },
  { name: "Kunafa", category: "Snacks & Sweets", portion: "1 slice (100g)", carbs: 50 },
  { name: "Chocolate bar (milk)", category: "Snacks & Sweets", portion: "1 bar (44g)", carbs: 26 },
  { name: "Cookies (plain)", category: "Snacks & Sweets", portion: "3 cookies (30g)", carbs: 21 },
  { name: "Potato chips", category: "Snacks & Sweets", portion: "1 small bag (28g)", carbs: 15 },
  { name: "Popcorn", category: "Snacks & Sweets", portion: "1 cup popped (8g)", carbs: 6 },
  { name: "Honey", category: "Snacks & Sweets", portion: "1 tbsp (21g)", carbs: 17 },
  { name: "Sugar, white", category: "Snacks & Sweets", portion: "1 tsp (4g)", carbs: 4 },
  { name: "Jam/marmalade", category: "Snacks & Sweets", portion: "1 tbsp (20g)", carbs: 13 },
  { name: "Granola bar", category: "Snacks & Sweets", portion: "1 bar (35g)", carbs: 22 },
  { name: "Donut, glazed", category: "Snacks & Sweets", portion: "1 medium (60g)", carbs: 34 },

  // Nuts & Seeds (mostly low-carb)
  { name: "Almonds", category: "Nuts & Seeds", portion: "1 oz / 23 nuts (28g)", carbs: 6 },
  { name: "Peanuts", category: "Nuts & Seeds", portion: "1 oz (28g)", carbs: 5 },
  { name: "Cashews", category: "Nuts & Seeds", portion: "1 oz (28g)", carbs: 9 },
  { name: "Peanut butter", category: "Nuts & Seeds", portion: "2 tbsp (32g)", carbs: 7 },

  // Beverages
  { name: "Orange juice", category: "Beverages", portion: "1 cup (248g)", carbs: 26 },
  { name: "Apple juice", category: "Beverages", portion: "1 cup (248g)", carbs: 28 },
  { name: "Cola (regular)", category: "Beverages", portion: "1 can (355ml)", carbs: 39 },
  { name: "Sports drink", category: "Beverages", portion: "1 bottle (500ml)", carbs: 34 },
  { name: "Sugarcane juice", category: "Beverages", portion: "1 cup (240ml)", carbs: 30 },
  { name: "Karkade (hibiscus tea, sweetened)", category: "Beverages", portion: "1 cup (240ml)", carbs: 20 },
  { name: "Tea, unsweetened", category: "Beverages", portion: "1 cup (240ml)", carbs: 0 },
  { name: "Coffee, black", category: "Beverages", portion: "1 cup (240ml)", carbs: 0 },
  { name: "Glucose tablets", category: "Beverages", portion: "3 tablets (12g)", carbs: 12 },
  { name: "Diet soda", category: "Beverages", portion: "1 can (355ml)", carbs: 0 },

  // Youffy Carbs reference — Arabic food & carb database provided by the user
  // الحلويات
  { name: "ايس كريم شوكوالته", category: "الحلويات", portion: "1 سكوب", carbs: 10 },
  { name: "ايس كريم فانيليا", category: "الحلويات", portion: "1 سكوب", carbs: 9 },
  { name: "بان كيك", category: "الحلويات", portion: "حبة متوسطة (45 جم)", carbs: 20 },
  { name: "بسبوسة", category: "الحلويات", portion: "قطعة صغيرة (23 جم)", carbs: 15 },
  { name: "بقلاوة", category: "الحلويات", portion: "25 جم", carbs: 15 },
  { name: "تشيز كيك", category: "الحلويات", portion: "قطعة صغيره (100 جم)", carbs: 35 },
  { name: "تورتيال سادة", category: "الحلويات", portion: "واحدة كبيره ( 65  )", carbs: 35 },
  { name: "جيلي", category: "الحلويات", portion: "3 معالق", carbs: 13 },
  { name: "حالوة طحينية", category: "الحلويات", portion: "30 جم", carbs: 15 },
  { name: "حلوة طحينية", category: "الحلويات", portion: "100 جم", carbs: 50 },
  { name: "حلى التراميسو", category: "الحلويات", portion: "قطعة صغيره (45 جم)", carbs: 12 },
  { name: "حلى التوفي", category: "الحلويات", portion: "قطعة صغيره (50 جم)", carbs: 24 },
  { name: "قطعة براونيز 2  انش", category: "الحلويات", portion: "واحده", carbs: 22 },
  { name: "كسترد  كريم كرامل", category: "الحلويات", portion: "½ كوب", carbs: 10 },
  { name: "كوكيز  شيكولاتة", category: "الحلويات", portion: "حبة واحدة متوسطة", carbs: 30 },
  { name: "كيك بالشيكولاتة", category: "الحلويات", portion: "قطعة صغيرة (40 جم)", carbs: 21 },
  { name: "كيكة جزر", category: "الحلويات", portion: "قطعة صغيرة (50 جم)", carbs: 23 },
  { name: "لقيمات", category: "الحلويات", portion: "3 حبات", carbs: 15 },
  { name: "مفن ساده", category: "الحلويات", portion: "قطعة متوسطة (102 جم)", carbs: 49 },
  { name: "نوتيال", category: "الحلويات", portion: "1 ملعقة طعام", carbs: 10 },
  { name: "وافل", category: "الحلويات", portion: "قطعة متوسطة", carbs: 15 },
  // خضروات
  { name: "بازلاء خضراء", category: "خضروات", portion: "½ كوب", carbs: 15 },
  { name: "بصل", category: "خضروات", portion: "1 حبة", carbs: 5 },
  { name: "بطاطس متوسطة", category: "خضروات", portion: "1 حبة", carbs: 15 },
  { name: "تبولة", category: "خضروات", portion: "½ كوب", carbs: 5 },
  { name: "جزر", category: "خضروات", portion: "2 حبة", carbs: 5 },
  { name: "خضار مطبوخة", category: "خضروات", portion: "½ كوب", carbs: 5 },
  { name: "ذرة", category: "خضروات", portion: "½ كوب", carbs: 15 },
  { name: "سلطة خضراء", category: "خضروات", portion: "1 كوب", carbs: 5 },
  { name: "طماطم", category: "خضروات", portion: "1 حبة", carbs: 5 },
  { name: "فاصوياء", category: "خضروات", portion: "ثلث كوب", carbs: 15 },
  { name: "فتوش", category: "خضروات", portion: "¾ كوب", carbs: 5 },
  { name: "فلفل رومي", category: "خضروات", portion: "1 حبة", carbs: 5 },
  { name: "قرع", category: "خضروات", portion: "1 كوب", carbs: 15 },
  // الشوربات
  { name: "شوربة البصل", category: "الشوربات", portion: "1 كوب", carbs: 7 },
  { name: "شوربة البصل الفرنسية", category: "الشوربات", portion: "كوب", carbs: 15 },
  { name: "شوربة الخضار", category: "الشوربات", portion: "1 كوب", carbs: 10 },
  { name: "شوربة الدجاج", category: "الشوربات", portion: "1 كوب", carbs: 4 },
  { name: "شوربة الطماطم", category: "الشوربات", portion: "1 كوب", carbs: 10 },
  { name: "شوربة المشروم", category: "الشوربات", portion: "1 كوب", carbs: 5 },
  { name: "شوربة خضار", category: "الشوربات", portion: "كوب", carbs: 15 },
  { name: "شوربة طماطم بالكريمة", category: "الشوربات", portion: "كوب", carbs: 20 },
  { name: "شوربة عدس", category: "الشوربات", portion: "كوب", carbs: 30 },
  { name: "شوربة فطر بالكريمة", category: "الشوربات", portion: "كوب", carbs: 15 },
  { name: "شوربة كريمة", category: "الشوربات", portion: "1 كوب", carbs: 15 },
  { name: "شوربة مرق دجاج صافية", category: "الشوربات", portion: "كوب", carbs: 1 },
  { name: "شوربة ملوخية", category: "الشوربات", portion: "كوب", carbs: 7.5 },
  // الطبخات
  { name: "أصابع الدجاج المقلي", category: "الطبخات", portion: "6 أصابع", carbs: 15 },
  { name: "إندومي بنكهة الدجاج", category: "الطبخات", portion: "المغلف الواحد", carbs: 48.8 },
  { name: "إيدام خضار بالكاري", category: "الطبخات", portion: "1 كوب", carbs: 19 },
  { name: "إيدام دجاج تكا مساال", category: "الطبخات", portion: "¾ كوب", carbs: 9 },
  { name: "الكسكس", category: "الطبخات", portion: "¼ كوب", carbs: 15 },
  { name: "بطاطس مقلية", category: "الطبخات", portion: "100 جم", carbs: 37.5 },
  { name: "بطاطس مقلية", category: "الطبخات", portion: "6 أصابع", carbs: 15 },
  { name: "بطاطس مهروسة", category: "الطبخات", portion: "½ كوب", carbs: 15 },
  { name: "جريش", category: "الطبخات", portion: "ملعقة طعام", carbs: 1.8 },
  { name: "رز بخاري", category: "الطبخات", portion: "6 مالعق", carbs: 15 },
  { name: "رز برياني", category: "الطبخات", portion: "3 مالعق", carbs: 15 },
  { name: "رز كبسة", category: "الطبخات", portion: "6 مالعق", carbs: 15 },
  { name: "رز مع خضار مشكلة", category: "الطبخات", portion: "5 مالعق", carbs: 15 },
  { name: "رز مندي", category: "الطبخات", portion: "6 مالعق", carbs: 15 },
  { name: "زالبية", category: "الطبخات", portion: "3 مالعق", carbs: 15 },
  { name: "ساندوتش شيش كباب", category: "الطبخات", portion: "1 خبز شامي كبير", carbs: 50 },
  { name: "ساندوتش فالفل", category: "الطبخات", portion: "1 خبز شامي كبير", carbs: 59 },
  { name: "ساندوتش كباب دونر", category: "الطبخات", portion: "1 خبز شامي كبير", carbs: 50 },
  { name: "سليق", category: "الطبخات", portion: "7 مالعق", carbs: 15 },
  { name: "سوشي", category: "الطبخات", portion: "قطعتين", carbs: 19 },
  { name: "شاورما دجاج أو لحم صغير", category: "الطبخات", portion: "50 جم", carbs: 45 },
  { name: "صيادية", category: "الطبخات", portion: "6 مالعق", carbs: 15 },
  { name: "فتة", category: "الطبخات", portion: "150 جم", carbs: 15 },
  { name: "فوتوتشيني", category: "الطبخات", portion: "½ كوب", carbs: 20 },
  { name: "قرصان", category: "الطبخات", portion: "120 جم", carbs: 15 },
  { name: "محشي فلفل أحمر", category: "الطبخات", portion: "126.2 جم", carbs: 15 },
  { name: "محشي كوسا", category: "الطبخات", portion: "3 حبات متوسطة", carbs: 15 },
  { name: "محشي ورق عنب", category: "الطبخات", portion: "4-3 حبات", carbs: 15 },
  { name: "مرقوق", category: "الطبخات", portion: "144 جم", carbs: 15 },
  { name: "مسقعة الباذنجان", category: "الطبخات", portion: "172 جم", carbs: 15 },
  { name: "مطازيز", category: "الطبخات", portion: "100 جم", carbs: 15 },
  { name: "مكرونة بالباشميل", category: "الطبخات", portion: "قطعة بح  راحة الكف", carbs: 33 },
  { name: "مكرونة بالجبنة", category: "الطبخات", portion: "1 كوب", carbs: 45 },
  { name: "نودلز بالدجاج", category: "الطبخات", portion: "½ كوب", carbs: 22 },
  { name: "هريس", category: "الطبخات", portion: "7 مالعق", carbs: 15 },
  // فواكه
  { name: "برتقال متوسطة", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "بطيخ", category: "فواكه", portion: "1 شريحة", carbs: 15 },
  { name: "تفاح متوسطة", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "تمر", category: "فواكه", portion: "3-2 حبات", carbs: 15 },
  { name: "جريب فروت كبيرة", category: "فواكه", portion: "½ حبة", carbs: 15 },
  { name: "جوافة كبيرة", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "خوخ متوسطة", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "رمان", category: "فواكه", portion: "½ حبة", carbs: 15 },
  { name: "طعام زبيب", category: "فواكه", portion: "2 ملعقة", carbs: 15 },
  { name: "عنب صغيرة", category: "فواكه", portion: "7 حبات", carbs: 15 },
  { name: "فراولة صغيرة", category: "فواكه", portion: "6 حبات", carbs: 15 },
  { name: "فواكه مجففة", category: "فواكه", portion: "¼ كوب", carbs: 15 },
  { name: "فواكه معلبة", category: "فواكه", portion: "½ كوب", carbs: 15 },
  { name: "كمثرى متوسطة", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "كيوي", category: "فواكه", portion: "حبة", carbs: 15 },
  { name: "مانجو كبيرة", category: "فواكه", portion: "½ حبة", carbs: 15 },
  { name: "مشمش طازج أو مجفف", category: "فواكه", portion: "4 حبات", carbs: 15 },
  { name: "موزة كبيرة", category: "فواكه", portion: "½", carbs: 15 },
  // المرطبات
  { name: "بيبسي أو كوكا كوال عادي", category: "المرطبات", portion: "علبة 330 مل", carbs: 40 },
  { name: "سبرايت", category: "المرطبات", portion: "علبة 330 مل", carbs: 40 },
  { name: "قهوة لاتيه بالحليب", category: "المرطبات", portion: "مل 235", carbs: 9 },
  { name: "كابتشينو صغير", category: "المرطبات", portion: "مل 235", carbs: 8 },
  { name: "ميلك شيك بالشوكوالته", category: "المرطبات", portion: "مل 340", carbs: 40 },
  { name: "ميلك شيك فانيال", category: "المرطبات", portion: "مل 340", carbs: 40 },
  { name: "هوت شكوليت", category: "المرطبات", portion: "مل 235", carbs: 25 },
  // المعجنات
  { name: "بيتزا", category: "المعجنات", portion: "قطعة واحدة", carbs: 30 },
  { name: "سبرينق رول", category: "المعجنات", portion: "حبة واحدة", carbs: 13 },
  { name: "سمبوسة خضار", category: "المعجنات", portion: "حبة واحدة", carbs: 8 },
  { name: "سمبوسة لحم أو دجاج", category: "المعجنات", portion: "حبة واحدة", carbs: 7 },
  { name: "كبة مقلية", category: "المعجنات", portion: "حبة واحدة", carbs: 10 },
  { name: "مطبق", category: "المعجنات", portion: "5 حبات", carbs: 15 },
  { name: "منتو", category: "المعجنات", portion: "5 حبات", carbs: 15 },
  { name: "ورق عنب", category: "المعجنات", portion: "3 حبات", carbs: 15 },
  { name: "يغموش", category: "المعجنات", portion: "3 حبات", carbs: 15 },
  // المقبالت والسلطات
  { name: "تبولة", category: "المقبالت والسلطات", portion: "¾ كوب", carbs: 16 },
  { name: "سلطة الخيار باللبن", category: "المقبالت والسلطات", portion: "½ كوب", carbs: 8 },
  { name: "سلطة الذرة", category: "المقبالت والسلطات", portion: "½ كوب", carbs: 14 },
  { name: "سلطة بطاطا بارده", category: "المقبالت والسلطات", portion: "1 كوب", carbs: 41 },
  { name: "فتوش", category: "المقبالت والسلطات", portion: "1 كوب", carbs: 24 },
  { name: "فول مدمس", category: "المقبالت والسلطات", portion: "½ كوب", carbs: 24 },
  { name: "كينوا متبلة", category: "المقبالت والسلطات", portion: "¼ كوب", carbs: 30 },
  { name: "متبل الباذنجان", category: "المقبالت والسلطات", portion: "1 كوب", carbs: 20 },
  // المكسرات والبذور
  { name: "بذور البطيخ", category: "المكسرات والبذور", portion: "كوبان", carbs: 14 },
  { name: "بذور تباع الشمس محمصة، بدون ملح", category: "المكسرات والبذور", portion: "كوب", carbs: 11 },
  { name: "جوز الهند، مسحوق", category: "المكسرات والبذور", portion: "كوبان", carbs: 12 },
  { name: "جوز مقشر غير مملح", category: "المكسرات والبذور", portion: "كوب", carbs: 12 },
  { name: "حمص مقشر", category: "المكسرات والبذور", portion: "¼ كوب", carbs: 17 },
  { name: "سمسم", category: "المكسرات والبذور", portion: "4 مالعق طعام", carbs: 15 },
  { name: "فستق غير مملح", category: "المكسرات والبذور", portion: "كوب", carbs: 13 },
  { name: "فول سوداني مقشر غير مملح", category: "المكسرات والبذور", portion: "100 حبة", carbs: 10 },
  { name: "كستناء  أبو فروة", category: "المكسرات والبذور", portion: "4 حبات", carbs: 15 },
  { name: "لوز", category: "المكسرات والبذور", portion: "60 حبة", carbs: 15 },
  { name: "مكسرات مشكلة مالحة", category: "المكسرات والبذور", portion: "8 حبات", carbs: 28 },
  // برجر كينج
  { name: "برجر كينج- بطاطس محمرة -صغيرة", category: "برجر كينج", portion: "عبوة", carbs: 44 },
  { name: "برجر كينج- بطاطس محمرة -كبيرة", category: "برجر كينج", portion: "عبوة", carbs: 69 },
  { name: "برجر كينج- بطاطس محمرة -وسط", category: "برجر كينج", portion: "عبوة", carbs: 56 },
  { name: "برجر كينج- تشكن تندرز", category: "برجر كينج", portion: "قطعة", carbs: 2.5 },
  { name: "برجر كينج- حلقات البصل صغير", category: "برجر كينج", portion: "عبوة", carbs: 36 },
  { name: "برجر كينج- سلطة كنج الدجاج- فراخ مشوية", category: "برجر كينج", portion: "عبوة", carbs: 9 },
  { name: "برجر كينج- سلطة كنج الدجاج-تندر كريسب شيكن", category: "برجر كينج", portion: "عبوة", carbs: 28 },
  { name: "برجر كينج- وابر جونيور", category: "برجر كينج", portion: "عدد واحد", carbs: 29 },
  { name: "برجر كينج- وابر/دوبل وابر", category: "برجر كينج", portion: "عدد واحد", carbs: 51 },
  // بروتينات
  { name: "بيض", category: "بروتينات", portion: "عدد واحد", carbs: 0 },
  // بسكويت
  { name: "بسكويت HobNobs", category: "بسكويت", portion: "100 جم", carbs: 61 },
  { name: "بسكويت HobNobs", category: "بسكويت", portion: "عبوة", carbs: 182.7 },
  { name: "بسكويت HobNobs", category: "بسكويت", portion: "قطعة", carbs: 8.9 },
  { name: "بسكويت الشاي لوكس الوزن 35    --- 8", category: "بسكويت", portion: "عبوة", carbs: 25.55 },
  { name: "بسكويت الشاي لوكس الوزن 35    --- 8 قطع", category: "بسكويت", portion: "قطعة", carbs: 3.2 },
  { name: "بسكويت بوريو 25", category: "بسكويت", portion: "4 قطع بسكويت", carbs: 15 },
  { name: "بسكويت بيمبو 25", category: "بسكويت", portion: "قطعة", carbs: 15 },
  { name: "بسكويت دايجستيف بالشوكولتة", category: "بسكويت", portion: "عدد واحد", carbs: 11 },
  { name: "بسكويت دايجستيف سادة", category: "بسكويت", portion: "عدد واحد", carbs: 10 },
  { name: "بسكويت لمبادا بالليمون 6 قطع ،الوزن 22", category: "بسكويت", portion: "عبوة", carbs: 15.4 },
  { name: "بسكويت لمبادا بالليمون 6 قطع ،الوزن 22", category: "بسكويت", portion: "قطعة", carbs: 2.5 },
  { name: "بسكويت لمبادا جولد", category: "بسكويت", portion: "قطعة", carbs: 23 },
  { name: "بسكويت لمبادا رقائق الهشة بكريمة البندق 6 قطع،", category: "بسكويت", portion: "قطعة", carbs: 4.7 },
  { name: "بسكويت لمبادا رقائق الهشة بكريمة البندق 6 قطع،", category: "بسكويت", portion: "عبوة", carbs: 28.7 },
  { name: "بسكويت لمبادا ويفر بالشوكولاتة 6قطع .. الوزن 27 جر", category: "بسكويت", portion: "عبوة", carbs: 18.9 },
  { name: "بسكويت لمبادا ويفر بالشوكولاتة 6قطع .. الوزن 27 جر", category: "بسكويت", portion: "قطعة", carbs: 3.2 },
  { name: "بسكويت لمبادا ويفر محشو بكريمة الشيكولتة 6 قطع،", category: "بسكويت", portion: "عبوة", carbs: 35 },
  { name: "بسكويت لمبادا ويفر محشو بكريمة الشيكولتة 6 قطع،", category: "بسكويت", portion: "قطعة", carbs: 5.8 },
  { name: "بسكويت مستورد creamkakao Loacker إيطالي الوزن 45 ج", category: "بسكويت", portion: "عبوة", carbs: 26.1 },
  { name: "بسكويت مستورد creamkakao Loacker إيطالي الوزن 45 ج", category: "بسكويت", portion: "قطعة", carbs: 3.2 },
  { name: "بسكويت مستورد إيطالي milk loacker ، الوزن 45", category: "بسكويت", portion: "عبوة", carbs: 24.4 },
  { name: "بسكويت مستورد إيطالي milk loacker ، الوزن 45", category: "بسكويت", portion: "قطعة", carbs: 3.05 },
  { name: "بسكويت مملح تاك 25", category: "بسكويت", portion: "5 قطع بسكويت", carbs: 15 },
  { name: "بسكويت نواعم 25", category: "بسكويت", portion: "4 قطع", carbs: 15 },
  // بقوليات
  { name: "الحمص  مسلوق", category: "بقوليات", portion: "100 جم", carbs: 27.42 },
  { name: "بازلاء خضراء نيئة", category: "بقوليات", portion: "100 جم", carbs: 14.5 },
  { name: "بسلة خضراء مسلوقة", category: "بقوليات", portion: "100 جم", carbs: 14.3 },
  { name: "بسلة خضراء مسلوقة", category: "بقوليات", portion: "كوب", carbs: 23 },
  { name: "شوفان", category: "بقوليات", portion: "100 جم", carbs: 66.3 },
  { name: "طعمية / فلافل", category: "بقوليات", portion: "100 جم", carbs: 31 },
  { name: "طعمية / فلافل", category: "بقوليات", portion: "عدد واحد", carbs: 5 },
  { name: "طعمية / فلافل", category: "بقوليات", portion: "3 حبات", carbs: 15 },
  { name: "عدس  مسلوق", category: "بقوليات", portion: "100 جم", carbs: 20.1 },
  { name: "عدس نيء", category: "بقوليات", portion: "100 جم", carbs: 60 },
  { name: "فاصوليا بيضاء  مسلوق", category: "بقوليات", portion: "100 جم", carbs: 25.1 },
  { name: "فاصوليا حمراء نيء", category: "بقوليات", portion: "100 جم", carbs: 60 },
  { name: "فول  نيء", category: "بقوليات", portion: "100 جم", carbs: 58.29 },
  { name: "فول سوداني", category: "بقوليات", portion: "100 جم", carbs: 21 },
  { name: "فول مدمس", category: "بقوليات", portion: "كوب", carbs: 33 },
  { name: "لوبيا", category: "بقوليات", portion: "100 جم", carbs: 11.5 },
  // حبوب
  { name: "بران فليكس", category: "حبوب", portion: "100 جم", carbs: 70 },
  { name: "برغل  نيء", category: "حبوب", portion: "كوب", carbs: 106 },
  { name: "بليلة", category: "حبوب", portion: "1 كوب", carbs: 15 },
  { name: "بليلة", category: "حبوب", portion: "ملعقة طعام", carbs: 7.5 },
  { name: "ترمس", category: "حبوب", portion: "100 جم", carbs: 14.3 },
  { name: "ذرة صفراء مسلوقه  حب", category: "حبوب", portion: "كوب", carbs: 36 },
  { name: "سميد", category: "حبوب", portion: "كوب", carbs: 120 },
  { name: "طحين/دقيق أبيض", category: "حبوب", portion: "كوب", carbs: 95 },
  { name: "فشار", category: "حبوب", portion: "كوب", carbs: 5 },
  { name: "كورن فلكس  شيكولاتة", category: "حبوب", portion: "100 جم", carbs: 90 },
  { name: "كورن فلكس محل", category: "حبوب", portion: "100 جم", carbs: 90 },
  // الحلويات
  { name: "الهريسة بالمكسرات", category: "الحلويات", portion: "100 جم", carbs: 57 },
  { name: "تيراميسو", category: "الحلويات", portion: "100 جم", carbs: 33 },
  { name: "دانيت بودنج", category: "الحلويات", portion: "عبوة", carbs: 20 },
  { name: "فطير تفاح", category: "الحلويات", portion: "100 جم", carbs: 36 },
  { name: "كريم كاراميل", category: "الحلويات", portion: "100 جم", carbs: 22 },
  { name: "كستر", category: "الحلويات", portion: "100 جم", carbs: 15 },
  { name: "كوكيز بقطع شيكولاتة", category: "الحلويات", portion: "100 جم", carbs: 60 },
  { name: "مارشميلو", category: "الحلويات", portion: "100 جم", carbs: 81 },
  { name: "مالتيزرز - باكت37", category: "الحلويات", portion: "100 جم", carbs: 62 },
  { name: "مالتيزرز - باكت37", category: "الحلويات", portion: "عبوة", carbs: 23 },
  // خضروات
  { name: "السبانخ- مسلوقة و مصفاه بدون ملح", category: "خضروات", portion: "100 جم", carbs: 4 },
  { name: "القرع يقطين  مسلوق", category: "خضروات", portion: "100 جم", carbs: 4.9 },
  { name: "القرع يقطين  نيء", category: "خضروات", portion: "100 جم", carbs: 6.5 },
  { name: "القلقاس النيء", category: "خضروات", portion: "100 جم", carbs: 26.46 },
  { name: "بامية", category: "خضروات", portion: "100 جم", carbs: 4.6 },
  { name: "بروكولي مسلوقة", category: "خضروات", portion: "100 جم", carbs: 5 },
  { name: "بروكولي نيئة", category: "خضروات", portion: "100 جم", carbs: 7 },
  { name: "بسلة+جزر مطهية", category: "خضروات", portion: "ملعقة طعام", carbs: 7.5 },
  { name: "بطاطا حلوة نيء", category: "خضروات", portion: "100 جم", carbs: 20.1 },
  { name: "بطاطس بيوريه لبن+زبد", category: "خضروات", portion: "100 جم", carbs: 16.9 },
  { name: "بطاطس مسلوقة بالقشر", category: "خضروات", portion: "100 جم", carbs: 20.7 },
  { name: "بنجر", category: "خضروات", portion: "100 جم", carbs: 9.96 },
  { name: "جزر", category: "خضروات", portion: "100 جم", carbs: 9.6 },
  { name: "زيتون أخضر- مخلل", category: "خضروات", portion: "100 جم", carbs: 4 },
  { name: "زيتون كالماتا", category: "خضروات", portion: "100 جم", carbs: 3 },
  { name: "سلطة بطاطس بالمايونيز", category: "خضروات", portion: "100 جم", carbs: 11 },
  { name: "سلطة بطاطس بالمايونيز", category: "خضروات", portion: "كوب", carbs: 28 },
  { name: "سلطة طازجة مشكلة", category: "خضروات", portion: "100 جم", carbs: 3 },
  { name: "سلطة طازجة مشكلة", category: "خضروات", portion: "كوب", carbs: 4 },
  { name: "سيزر سالد", category: "خضروات", portion: "100 جم", carbs: 2 },
  { name: "طماطم مجففة", category: "خضروات", portion: "100 جم", carbs: 55 },
  { name: "طماطم مجففة", category: "خضروات", portion: "كوب", carbs: 30 },
  { name: "فاصوليا خضراء", category: "خضروات", portion: "100 جم", carbs: 7.1 },
  { name: "قرنبيط-زهرة مسلوقة", category: "خضروات", portion: "100 جم", carbs: 4 },
  { name: "قرنبيط-زهرة نيئة", category: "خضروات", portion: "100 جم", carbs: 5 },
  { name: "كوسا", category: "خضروات", portion: "100 جم", carbs: 3.4 },
  { name: "كول سلو", category: "خضروات", portion: "ملعقة طعام", carbs: 1 },
  { name: "ملفوف مسلوق", category: "خضروات", portion: "100 جم", carbs: 5 },
  { name: "ملفوف نيء", category: "خضروات", portion: "100 جم", carbs: 6 },
  { name: "ورق الملوخية قبل الطب", category: "خضروات", portion: "100 جم", carbs: 10 },
  // ستاربكس
  { name: "ستاربكس-فراباشينو فانيل بدون كريمة-وسط", category: "ستاربكس", portion: "كوب", carbs: 51 },
  { name: "ستاربكس-فراباشينو كاراميل بدون كريمة-", category: "ستاربكس", portion: "كوب", carbs: 45 },
  { name: "ستاربكس-فراباشينو موكا بدون كريمة- وسط", category: "ستاربكس", portion: "كوب", carbs: 45.8 },
  // سكريات
  { name: "سكر أبيض", category: "سكريات", portion: "ملعقة طعام", carbs: 12 },
  { name: "سكر أبيض", category: "سكريات", portion: "ملعقة صغيرة", carbs: 4 },
  { name: "سكر أبيض مكعبات", category: "سكريات", portion: "قطعة", carbs: 2.3 },
  { name: "سكر بني", category: "سكريات", portion: "ملعقة طعام", carbs: 9 },
  { name: "سكر بني", category: "سكريات", portion: "ملعقة صغيرة", carbs: 3 },
  { name: "سكر بودرة", category: "سكريات", portion: "ملعقة صغيرة", carbs: 2.5 },
  { name: "سكر بودرة", category: "سكريات", portion: "ملعقة طعام", carbs: 8 },
  { name: "عسل", category: "سكريات", portion: "ملعقة صغير", carbs: 5.5 },
  { name: "عسل أسود", category: "سكريات", portion: "ملعقة طعام", carbs: 14.9 },
  { name: "عسل بانكيك", category: "سكريات", portion: "ملعقة صغير", carbs: 4 },
  { name: "عسل بانكيك", category: "سكريات", portion: "ملعقة طعام", carbs: 13 },
  { name: "عسل طبيعي", category: "سكريات", portion: "ملعقة طعام", carbs: 17 },
  { name: "مربى", category: "سكريات", portion: "ملعقة طعام", carbs: 13 },
  // شوكولاتة
  { name: "شوكولاتة تويكس .. Twix2bars وزنهم 58", category: "شوكولاتة", portion: "عبوة", carbs: 28.2 },
  { name: "شوكولاتة Maltesers    37", category: "شوكولاتة", portion: "1 حصة", carbs: 62 },
  { name: "شوكولاتة Maltesers    37", category: "شوكولاتة", portion: "عبوة", carbs: 23 },
  { name: "شوكولاتة باونتي ... مستوردة وزن 57", category: "شوكولاتة", portion: "عبوة", carbs: 33 },
  { name: "شوكولاتة باونتي ... مستوردة وزن 57", category: "شوكولاتة", portion: "قطعة", carbs: 16.4 },
  { name: "شوكولاتة تويكس .. Twix2bars وزنهم 58", category: "شوكولاتة", portion: "قطعة", carbs: 14.1 },
  { name: "شوكولاتة توينكيز كيكة بكريمة وزن 35    twinkies", category: "شوكولاتة", portion: "عبوة", carbs: 23 },
  { name: "شوكولاتة جلكسي MILK SMOOTHوزن 40    6مكعبات", category: "شوكولاتة", portion: "عبوة", carbs: 54.76 },
  { name: "شوكولاتة جلكسي MILK SMOOTHوزن 40    المكعب الواح", category: "شوكولاتة", portion: "عدد واحد", carbs: 9.12 },
  { name: "شوكولاتة سنيكرز بالفول السوداني Snickersوزن 57", category: "شوكولاتة", portion: "عبوة", carbs: 32 },
  { name: "شوكولاتة كادبوري 12.5", category: "شوكولاتة", portion: "صابع", carbs: 7.5 },
  { name: "شوكولاتة كادبوري كبير 25", category: "شوكولاتة", portion: "3 مكعبات", carbs: 15 },
  { name: "شوكولاتة كادبوري وسط 25", category: "شوكولاتة", portion: "قطعة", carbs: 15 },
  { name: "شوكولاتة كتاكيتو 35", category: "شوكولاتة", portion: "قطعة", carbs: 15 },
  { name: "شوكولاتة كورونا 30", category: "شوكولاتة", portion: "باكو 6 مكعبات", carbs: 15 },
  { name: "شوكولاتة كورونا ويفر صغير 25", category: "شوكولاتة", portion: "2 صابع", carbs: 15 },
  { name: "شوكولاتة كورونا ويفر كبير 20", category: "شوكولاتة", portion: "1 صابع", carbs: 15 },
  { name: "شوكولاتة كيت كات الصغيرة  2bars", category: "شوكولاتة", portion: "عبوة", carbs: 11.5 },
  { name: "شوكولاتة كيك توينكيز 25", category: "شوكولاتة", portion: "قطعة", carbs: 15 },
  { name: "شوكولاتة كيمو كونو", category: "شوكولاتة", portion: "قطعة", carbs: 15 },
  { name: "شوكولاتة ليون بارمستوردة بولندي .... Lion Nestle ال", category: "شوكولاتة", portion: "عبوة", carbs: 21.9 },
  { name: "شوكولاتة ماندولين 25", category: "شوكولاتة", portion: "قطعة", carbs: 15 },
  { name: "شوكولاتة بودرة غير محلة", category: "شوكولاتة", portion: "ملعقة طعام", carbs: 2.9 },
  // صوص وصلصة
  { name: "شيلي صوص", category: "صوص وصلصة", portion: "ملعقة طعام", carbs: 5 },
  { name: "صلصة الباربكيو", category: "صوص وصلصة", portion: "32 جم", carbs: 12 },
  { name: "صلصة التوت البري", category: "صوص وصلصة", portion: "كوب", carbs: 108 },
  { name: "صوص الصويا", category: "صوص وصلصة", portion: "1 ملعقة طعام", carbs: 3 },
  { name: "صوص باربكيو", category: "صوص وصلصة", portion: "كوب", carbs: 32 },
  { name: "صوص تارتار", category: "صوص وصلصة", portion: "100 جم", carbs: 14 },
  { name: "صوص سلطة جاهز ايطالي", category: "صوص وصلصة", portion: "كوب", carbs: 24.5 },
  { name: "صوص سلطة جاهز ايطالي", category: "صوص وصلصة", portion: "ملعقة طعام", carbs: 1.5 },
  { name: "صوص سلطة جاهز ثاوزن آيلند", category: "صوص وصلصة", portion: "كوب", carbs: 40 },
  { name: "صوص سلطة جاهز ثاوزن آيلند", category: "صوص وصلصة", portion: "ملعقة طعام", carbs: 3 },
  { name: "صوص مسترد أصفر", category: "صوص وصلصة", portion: "كوب", carbs: 15.5 },
  { name: "صوص مسترد أصفر", category: "صوص وصلصة", portion: "ملعقة صغيرة", carbs: 0.4 },
  { name: "طحينة", category: "صوص وصلصة", portion: "1 ملعقة طعام", carbs: 3 },
  { name: "كاتشب", category: "صوص وصلصة", portion: "ملعقة طعام", carbs: 4 },
  // عصير
  { name: "عصير تانج البودرة", category: "عصير", portion: "ملعقة طعام", carbs: 14 },
  { name: "عصير جهينة jump وزن 200مل", category: "عصير", portion: "عبوة", carbs: 16 },
  { name: "عصير جهينة مانجو 200 مل", category: "عصير", portion: "عبوة", carbs: 30.2 },
  { name: "عصير خضار", category: "عصير", portion: "½ كوب", carbs: 5 },
  { name: "عصير طماطم", category: "عصير", portion: "½ كوب", carbs: 5 },
  { name: "عصير غير محلى", category: "عصير", portion: "½ كوب", carbs: 15 },
  { name: "عصير فواكه", category: "عصير", portion: "كوب", carbs: 30 },
  // فواكه
  { name: "أفوكادو", category: "فواكه", portion: "100 جم", carbs: 9 },
  { name: "أناناس شراب ثقيل", category: "فواكه", portion: "كوب", carbs: 52 },
  { name: "أناناس طازج", category: "فواكه", portion: "100 جم", carbs: 13 },
  { name: "أناناس في عصيره", category: "فواكه", portion: "كوب", carbs: 40 },
  { name: "أناناس في ماء شريحة دائرية", category: "فواكه", portion: "قطعة", carbs: 4 },
  { name: "اليوسفي", category: "فواكه", portion: "100 جم", carbs: 13 },
  { name: "بابايا", category: "فواكه", portion: "100 جم", carbs: 9.8 },
  { name: "برتقال", category: "فواكه", portion: "100 جم", carbs: 9 },
  { name: "برتقال بسرة", category: "فواكه", portion: "100 جم", carbs: 12.5 },
  { name: "برقوق", category: "فواكه", portion: "100 جم", carbs: 11 },
  { name: "برقوق مجف", category: "فواكه", portion: "100 جم", carbs: 63.88 },
  { name: "بطيخ", category: "فواكه", portion: "100 جم", carbs: 7.6 },
  { name: "بلح/تمر", category: "فواكه", portion: "100 جم", carbs: 75 },
  { name: "توت أحمر", category: "فواكه", portion: "100 جم", carbs: 12 },
  { name: "توت أزرق", category: "فواكه", portion: "100 جم", carbs: 15 },
  { name: "توت أسود", category: "فواكه", portion: "100 جم", carbs: 10 },
  { name: "توت بري", category: "فواكه", portion: "100 جم", carbs: 12.2 },
  { name: "توت شراب ثقيل", category: "فواكه", portion: "كوب", carbs: 60 },
  { name: "توت شراب خفيف", category: "فواكه", portion: "كوب", carbs: 52 },
  { name: "تين", category: "فواكه", portion: "100 جم", carbs: 19.2 },
  { name: "تين شوكي", category: "فواكه", portion: "عدد واحد", carbs: 9 },
  { name: "تين شوكي", category: "فواكه", portion: "كوب", carbs: 14 },
  { name: "تين مجفف", category: "فواكه", portion: "عدد واحد", carbs: 5.4 },
  { name: "جريب فروت", category: "فواكه", portion: "100 جم", carbs: 8 },
  { name: "جوافة", category: "فواكه", portion: "100 جم", carbs: 14.3 },
  { name: "جوز الهند  مبشور غيرمحلي", category: "فواكه", portion: "100 جم", carbs: 26.7 },
  { name: "جوز الهند  مبشور محلي", category: "فواكه", portion: "100 جم", carbs: 47.7 },
  { name: "خوخ", category: "فواكه", portion: "100 جم", carbs: 10 },
  { name: "خوخ  شراب ثقيل", category: "فواكه", portion: "كوب", carbs: 52 },
  { name: "خوخ  شراب خفيف", category: "فواكه", portion: "كوب", carbs: 36 },
  { name: "خوخ نصف حبة  شراب خفيف - مصفاه", category: "فواكه", portion: "قطعة", carbs: 14 },
  { name: "رمان الحب", category: "فواكه", portion: "100 جم", carbs: 19 },
  { name: "زبيب فواكه مجففة", category: "فواكه", portion: "100 جم", carbs: 79 },
  { name: "عنب", category: "فواكه", portion: "100 جم", carbs: 18 },
  { name: "فراولة", category: "فواكه", portion: "100 جم", carbs: 8 },
  { name: "قراصيا  برقوق مجفف", category: "فواكه", portion: "عدد واحد", carbs: 5.4 },
  { name: "كرز", category: "فواكه", portion: "100 جم", carbs: 16 },
  { name: "كريز منزوع النواه شراب ثقيل", category: "فواكه", portion: "كوب", carbs: 54 },
  { name: "كريز منزوع النواه شراب خفيف", category: "فواكه", portion: "كوب", carbs: 44 },
  { name: "كمثرى", category: "فواكه", portion: "100 جم", carbs: 15.5 },
  { name: "كنتالوب", category: "فواكه", portion: "100 جم", carbs: 8.8 },
  { name: "كيوي", category: "فواكه", portion: "100 جم", carbs: 14.7 },
  { name: "لبن جوز الهند  طازج", category: "فواكه", portion: "100 جم", carbs: 5.5 },
  { name: "مانجو", category: "فواكه", portion: "100 جم", carbs: 17 },
  { name: "مشم  شراب", category: "فواكه", portion: "كوب", carbs: 56 },
  { name: "مشمش", category: "فواكه", portion: "100 جم", carbs: 11.2 },
  { name: "مشمشية مشمش مجف", category: "فواكه", portion: "100 جم", carbs: 57.5 },
  { name: "مشمشية مشمش مجفف", category: "فواكه", portion: "عدد واحد", carbs: 4.4 },
  { name: "موز", category: "فواكه", portion: "100 جم", carbs: 23 },
  // لحوم
  { name: "أصابع دجاج مقلي بالبقسماط", category: "لحوم", portion: "100 جم", carbs: 18 },
  { name: "أصابع سمك مقلي بالبقسماط", category: "لحوم", portion: "100 جم", carbs: 17 },
  { name: "بوفتيك /سكالوب بانيه", category: "لحوم", portion: "100 جم", carbs: 7 },
  { name: "تونا معلبة", category: "لحوم", portion: "عبوة", carbs: 0 },
  { name: "بري مقلي", category: "لحوم", portion: "100 جم", carbs: 12 },
  { name: "دجاج مسلوق", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "سلمي", category: "لحوم", portion: "100 جم", carbs: 2 },
  { name: "سمك بلطي نئ", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "سمك فيليه مقلي", category: "لحوم", portion: "100 جم", carbs: 8 },
  { name: "شرائح ديك رومي - تركي", category: "لحوم", portion: "100 جم", carbs: 4 },
  { name: "شرائح روست بيف", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "عصاج من لحم بقري مفروم  كوب", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "فراخ في الفرن/مشويه", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "فراخ محمره بدون تغطيه بقسماط", category: "لحوم", portion: "100 جم", carbs: 1 },
  { name: "كبدة بقر مطبوخة/متشوحه", category: "لحوم", portion: "100 جم", carbs: 5 },
  { name: "كبدة بقر مغطاه بالبقسماط و مقليه", category: "لحوم", portion: "100 جم", carbs: 13 },
  { name: "كبدة خروف مطبوخة", category: "لحوم", portion: "100 جم", carbs: 4 },
  { name: "كبدة عجل مطبوخة", category: "لحوم", portion: "100 جم", carbs: 5 },
  { name: "مورتاديل", category: "لحوم", portion: "100 جم", carbs: 3 },
  { name: "ناجتس/بانيه/فراح فيليه مغطاه بالبقسماط ومقليه", category: "لحوم", portion: "100 جم", carbs: 12 },
  // نشويات
  { name: "1 تورتيال صغيره", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "1 شريحة توست أبيض/ أسمر", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "½ صامولي", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "½ كوب اندومي", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "½ كوب كورن فليكس", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "¼ رغيف خبز أبيض/أسمر", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "2 قطعة شابورة", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "3 أكواب فشار", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "3 قطع مراصيع/ مصابيب", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "3 مالعق أرز برياني", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "6 مالعق أرز أو سليق", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "6 مالعق فول أو عدس", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "7 مالعق هريس", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "8 مالعق جريش", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "8 مالعق قرصان", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "8 مالعق مرقوق", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  { name: "8 مالعق مكرونة", category: "نشويات", portion: "حصة نشويات (1)", carbs: 15 },
  // مخبوزات
  { name: "وناتس ح  وسط  chocolate, مغطاه sugared or glaze", category: "مخبوزات", portion: "100 جم", carbs: 57.4 },
  { name: "وناتس ح  وسط مغطاه  chocolate, sugared or glaze", category: "مخبوزات", portion: "عدد واحد", carbs: 24.1 },
  { name: "pound cake دسم كيك", category: "مخبوزات", portion: "100 جم", carbs: 49 },
  { name: "باف باستري", category: "مخبوزات", portion: "100 جم", carbs: 32.86 },
  { name: "براوني", category: "مخبوزات", portion: "100 جم", carbs: 49.29 },
  { name: "بسكويت cookies  سادة", category: "مخبوزات", portion: "100 جم", carbs: 35.21 },
  { name: "بسكويت cookies  شوفان و زبيب", category: "مخبوزات", portion: "100 جم", carbs: 65.72 },
  { name: "بسكويت cookies  شيكولتة", category: "مخبوزات", portion: "100 جم", carbs: 63 },
  { name: "بقسماط أو كعك مطحون", category: "مخبوزات", portion: "100 جم", carbs: 72 },
  { name: "بقسماط طويل", category: "مخبوزات", portion: "عدد واحد", carbs: 7 },
  { name: "بيتزا كبيرة رفيعة 1/8", category: "مخبوزات", portion: "قطعة", carbs: 31 },
  { name: "بيتزا محشيه الطراف 100", category: "مخبوزات", portion: "100 جم", carbs: 30 },
  { name: "بيتزا وسط رفيعة 1/8", category: "مخبوزات", portion: "قطعة", carbs: 22 },
  { name: "بيتزا وسط سميكة 1/8", category: "مخبوزات", portion: "قطعة", carbs: 27 },
  { name: "خبز", category: "مخبوزات", portion: "100 جم", carbs: 50 },
  { name: "خبز توست أبيض ،شريحة رفيعة", category: "مخبوزات", portion: "عدد واحد", carbs: 9 },
  { name: "خبز توست أبيض ،شريحة سميكة", category: "مخبوزات", portion: "عدد واحد", carbs: 15 },
  { name: "خبز توست أسمر الحبة الكاملة ،شريحة رفيعة", category: "مخبوزات", portion: "عدد واحد", carbs: 12 },
  { name: "دانش بالجبنه", category: "مخبوزات", portion: "100 جم", carbs: 37.2 },
  { name: "دانش بالفواكه", category: "مخبوزات", portion: "100 جم", carbs: 47.8 },
  { name: "دانش بالمكسرات/زبيب", category: "مخبوزات", portion: "100 جم", carbs: 45.7 },
  { name: "دانكن دونت/ اكلير دونت", category: "مخبوزات", portion: "عدد واحد", carbs: 52 },
  { name: "دانكن دونت/ بطبقة شوكولتة", category: "مخبوزات", portion: "عدد واحد", carbs: 31 },
  { name: "دانكن دونت/ بوستون كريم", category: "مخبوزات", portion: "عدد واحد", carbs: 39 },
  { name: "دانكن دونت/ دونت حلقة سادة", category: "مخبوزات", portion: "عدد واحد", carbs: 25 },
  { name: "دانكن دونت/ دونت محشو بالجلي", category: "مخبوزات", portion: "عدد واحد", carbs: 36 },
  { name: "دانكن دونت/ كرواسون سادة", category: "مخبوزات", portion: "عدد واحد", carbs: 35 },
  { name: "دانكن دونت/ كور صغيرة\"منتشكين\"", category: "مخبوزات", portion: "عدد واحد", carbs: 7 },
  { name: "دوناتس ح  وسط مغطاه chocolate, sugared or glaze", category: "مخبوزات", portion: "عدد واحد", carbs: 24.1 },
  { name: "سكون سادة  كعك انجليزي", category: "مخبوزات", portion: "عدد واحد", carbs: 30 },
  { name: "سينامون رول", category: "مخبوزات", portion: "100 جم", carbs: 50 },
  { name: "عجينة سمبوسة جاهزة", category: "مخبوزات", portion: "عدد واحد", carbs: 5 },
  { name: "عيش شامي صغير  قطر 4 بوصة", category: "مخبوزات", portion: "100 جم", carbs: 58 },
  { name: "عيش شامي صغير  قطر 4 بوصة", category: "مخبوزات", portion: "عدد واحد", carbs: 18 },
  { name: "عيش شامي كبير  قطر 6.5 بوصة", category: "مخبوزات", portion: "100 جم", carbs: 56 },
  { name: "عيش شامي كبير  قطر 6.5 بوصة", category: "مخبوزات", portion: "عدد واحد", carbs: 33.4 },
  { name: "فطائر سبانخ", category: "مخبوزات", portion: "عدد واحد", carbs: 7.5 },
  { name: "كب كيك", category: "مخبوزات", portion: "100 جم", carbs: 53.4 },
  { name: "كب كيك", category: "مخبوزات", portion: "عدد واحد", carbs: 23 },
  { name: "كب كيك مع طبقة الت يل", category: "مخبوزات", portion: "عدد واحد", carbs: 28.9 },
  { name: "كرواسون ميني  شيكولاتة", category: "مخبوزات", portion: "100 جم", carbs: 50.49 },
  { name: "كرواسون ميني سادة /جبن/زبد", category: "مخبوزات", portion: "100 جم", carbs: 45.77 },
  { name: "كرواسون ميني سادة /جبن/زبد", category: "مخبوزات", portion: "قطعة", carbs: 13 },
  { name: "كرواسون ميني شيكولاتة", category: "مخبوزات", portion: "قطعة", carbs: 14.33 },
  { name: "كيك الجزر", category: "مخبوزات", portion: "100 جم", carbs: 39.61 },
  { name: "كيكة شيكولاتة", category: "مخبوزات", portion: "100 جم", carbs: 45.77 },
  { name: "مانتو", category: "مخبوزات", portion: "عدد واحد", carbs: 3.5 },
  { name: "ورقة الجالش", category: "مخبوزات", portion: "عدد واحد", carbs: 10 },
  { name: "يغمش", category: "مخبوزات", portion: "عدد واحد", carbs: 5 },
  // مشروبات
  { name: "شاي", category: "مشروبات", portion: "كوب", carbs: 0 },
  { name: "قهوة كابتشينو", category: "مشروبات", portion: "كوب", carbs: 6 },
  { name: "قهوة لاتيه", category: "مشروبات", portion: "كوب", carbs: 10 },
  { name: "ميلك شيك شوكولتة", category: "مشروبات", portion: "كوب", carbs: 50 },
  { name: "ميلك شيك شوكولتة", category: "مشروبات", portion: "مل100", carbs: 20 },
  { name: "ميلك شيك فانيل", category: "مشروبات", portion: "كوب", carbs: 40 },
  { name: "ميلك شيك فانيل", category: "مشروبات", portion: "مل100", carbs: 15 },
  { name: "نسكويك بودرة", category: "مشروبات", portion: "ملعقة طعام", carbs: 7 },
  // معلبات
  { name: "بنجر مخلل", category: "معلبات", portion: "كوب", carbs: 38 },
  { name: "حبوب ذر صفراء معلبة", category: "معلبات", portion: "100 جم", carbs: 18.6 },
  { name: "حبوب ذرة صفراء معلبة", category: "معلبات", portion: "كوب", carbs: 30 },
  { name: "خل بالساميك", category: "معلبات", portion: "ملعقة طعام", carbs: 2 },
  { name: "خل تفاح", category: "معلبات", portion: "ملعقة طعام", carbs: 0 },
  { name: "مخلل حلو", category: "معلبات", portion: "كوب", carbs: 85 },
  { name: "نوتيلل نكهة البندق", category: "معلبات", portion: "100 جم", carbs: 0.58 },
  { name: "نوتيلل نكهة البندق", category: "معلبات", portion: "ملعقة طعام", carbs: 11 },
  // مكدونالدز
  { name: "آبل باي - فطيرة التفاح", category: "مكدونالدز", portion: "الحصة: 0322", carbs: 29 },
  { name: "آيس كريم بالبسكويت", category: "مكدونالدز", portion: "واحد", carbs: 42 },
  { name: "آيس كريم صاندي شوكوالته", category: "مكدونالدز", portion: "الحصة: 29322", carbs: 58 },
  { name: "آيس كريم صاندي فراولة", category: "مكدونالدز", portion: "واحد", carbs: 56 },
  { name: "آيس كريم صاندي كراميل", category: "مكدونالدز", portion: "واحد", carbs: 67 },
  { name: "البطاطس", category: "مكدونالدز", portion: "صغير (وجبة األطفال)", carbs: 42 },
  { name: "البطاطس", category: "مكدونالدز", portion: "عادي", carbs: 60 },
  { name: "البطاطس", category: "مكدونالدز", portion: "كبير", carbs: 100 },
  { name: "البطاطس", category: "مكدونالدز", portion: "متوسط", carbs: 84 },
  { name: "بيج بركفاست", category: "مكدونالدز", portion: "واحد", carbs: 47 },
  { name: "بيج تايستي", category: "مكدونالدز", portion: "واحد", carbs: 53 },
  { name: "بيج ماك", category: "مكدونالدز", portion: "واحد", carbs: 41 },
  { name: "تشيز برجر", category: "مكدونالدز", portion: "واحد", carbs: 32 },
  { name: "تشيكن برجر", category: "مكدونالدز", portion: "واحد", carbs: 35 },
  { name: "تشيكن ماك  دجاج", category: "مكدونالدز", portion: "واحد", carbs: 51 },
  { name: "تشيكن ماك ناجت دجاج", category: "مكدونالدز", portion: "9 قطع", carbs: 25 },
  { name: "جراند تشيكن ديلوكس", category: "مكدونالدز", portion: "واحد", carbs: 74 },
  { name: "جراند تشيكن سبيشال", category: "مكدونالدز", portion: "واحد", carbs: 74 },
  { name: "جراند تشيكن كالسيك", category: "مكدونالدز", portion: "واحد", carbs: 69 },
  { name: "دبل تشيز برجر", category: "مكدونالدز", portion: "واحد", carbs: 33 },
  { name: "سبايسي ماك تشيكن", category: "مكدونالدز", portion: "واحد", carbs: 50 },
  { name: "كوب سبرايت", category: "مكدونالدز", portion: "16 أونصة", carbs: 34 },
  { name: "كوب سبرايت", category: "مكدونالدز", portion: "21 أونصة (مع ثلج)", carbs: 25 },
  { name: "كوب سبرايت", category: "مكدونالدز", portion: "21 أونصة (بدون ثلج)", carbs: 49 },
  { name: "كوب سبرايت", category: "مكدونالدز", portion: "32 أونصة", carbs: 72 },
  { name: "كوب فانتا", category: "مكدونالدز", portion: "16 أونصة", carbs: 47 },
  { name: "كوب فانتا", category: "مكدونالدز", portion: "21 أونصة (مع ثلج)", carbs: 34 },
  { name: "كوب فانتا", category: "مكدونالدز", portion: "21 أونصة (بدون ثلج)", carbs: 66 },
  { name: "كوب فانتا", category: "مكدونالدز", portion: "32 أونصة", carbs: 97 },
  { name: "كوب كوكاكوال", category: "مكدونالدز", portion: "16 أونصة", carbs: 35 },
  { name: "كوب كوكاكوال", category: "مكدونالدز", portion: "21 أونصة (مع ثلج)", carbs: 26 },
  { name: "كوب كوكاكوال", category: "مكدونالدز", portion: "21 أونصة (بدون ثلج)", carbs: 50 },
  { name: "كوب كوكاكوال", category: "مكدونالدز", portion: "32 أونصة", carbs: 74 },
  { name: "كوب كوكاكولا دايت", category: "مكدونالدز", portion: "كل األحجام", carbs: 0 },
  { name: "ماك أرابيا تشيكن  دجاج", category: "مكدونالدز", portion: "واحد", carbs: 47 },
  { name: "ماك تشيكن", category: "مكدونالدز", portion: "واحد", carbs: 49 },
  { name: "ماك رويال", category: "مكدونالدز", portion: "واحد", carbs: 47 },
  { name: "ماك فلوري اوريو", category: "مكدونالدز", portion: "واحد", carbs: 66 },
  { name: "ماك فلوري كيت كات", category: "مكدونالدز", portion: "1 حصة", carbs: 64 },
  { name: "ماك فيليه سمك", category: "مكدونالدز", portion: "واحد", carbs: 40 },
  { name: "ماك مافن بالبيض", category: "مكدونالدز", portion: "واحد", carbs: 33 },
  { name: "ماك مافن صوصج", category: "مكدونالدز", portion: "واحد", carbs: 32 },
  { name: "ماك مافن صوصج بالبيض", category: "مكدونالدز", portion: "واحد", carbs: 35 },
  { name: "مكدونالدز - أبل باي", category: "مكدونالدز", portion: "قطعة", carbs: 32 },
  { name: "مكدونالدز - بطاطس مقلية /وجبه الطفال", category: "مكدونالدز", portion: "عدد واحد", carbs: 12.7 },
  { name: "مكدونالدز - بطاطس مقلية صغيرة", category: "مكدونالدز", portion: "عبوة", carbs: 29 },
  { name: "مكدونالدز - بطاطس مقلية وسط", category: "مكدونالدز", portion: "عبوة (1)", carbs: 48 },
  { name: "مكدونالدز - بطاطس مقلية وسط", category: "مكدونالدز", portion: "عبوة (2)", carbs: 63 },
  { name: "مكدونالدز - بيج اند تاستي", category: "مكدونالدز", portion: "عدد واحد", carbs: 37 },
  { name: "مكدونالدز - بيج ماك", category: "مكدونالدز", portion: "عدد واحد", carbs: 45 },
  { name: "مكدونالدز - كوارتر باوند، بدون جبن", category: "مكدونالدز", portion: "عدد واحد", carbs: 37 },
  { name: "مكدونالدز - كوارتر باوند، جبن", category: "مكدونالدز", portion: "عدد واحد", carbs: 40 },
  { name: "مكدونالدز - ماك تشيكن", category: "مكدونالدز", portion: "عدد واحد", carbs: 40 },
  { name: "مكدونالدز - ماك دبل", category: "مكدونالدز", portion: "عدد واحد", carbs: 33 },
  { name: "مكدونالدز - ماك ناجتس", category: "مكدونالدز", portion: "عدد واحد", carbs: 3 },
  { name: "مكدونالدز - هابي ميل", category: "مكدونالدز", portion: "وجبة", carbs: 63 },
  { name: "مكدونالدز - هابي ميل ،برجر لحم / فراخ،بطاطس،مشروب عصير تفاح ب23- كارب", category: "مكدونالدز", portion: "وجبة", carbs: 84 },
  { name: "مكدونالدز -آيس كريم ،كونو أطفال", category: "مكدونالدز", portion: "عدد واحد", carbs: 8 },
  { name: "مكدونالدز -آيس كريم ،ماك فلوري ،m m&", category: "مكدونالدز", portion: "عدد واحد", carbs: 96 },
  { name: "مكدونالدز -آيس كريم ،ماك فلوري ،اوريو", category: "مكدونالدز", portion: "عدد واحد", carbs: 80 },
  { name: "مكدونالدز -آيس كريم صانداي، شيكولته", category: "مكدونالدز", portion: "عدد واحد", carbs: 54 },
  { name: "مكدونالدز -آيس كريم صانداي،فراولة", category: "مكدونالدز", portion: "عدد واحد", carbs: 49 },
  { name: "مكدونالدز -آيس كريم صانداي،كراميل", category: "مكدونالدز", portion: "عدد واحد", carbs: 60 },
  { name: "مكدونالدز -برجر جبن", category: "مكدونالدز", portion: "عدد واحد", carbs: 33 },
  { name: "مكدونالدز- ميلك شاك، شيكولته ، 360 مل", category: "مكدونالدز", portion: "عبوة", carbs: 76 },
  { name: "مكدونالدز- ميلك شاك، فراولة/فانيليا , 360 مل ،", category: "مكدونالدز", portion: "عبوة", carbs: 72.5 },
  { name: "ناجتس،بطاطس،مشروب  عصير تفاح", category: "مكدونالدز", portion: "وجبة", carbs: 23 },
  { name: "هاش براونز", category: "مكدونالدز", portion: "واحد", carbs: 15 },
  { name: "هوت كيك", category: "مكدونالدز", portion: "3 قطع", carbs: 54 },
  // مكسرات
  { name: "الكستناء", category: "مكسرات", portion: "100 جم", carbs: 53 },
  { name: "الكستناء", category: "مكسرات", portion: "قطعة", carbs: 5 },
  { name: "الكستناء", category: "مكسرات", portion: "كوب", carbs: 75.7 },
  { name: "اللوز", category: "مكسرات", portion: "100 جم", carbs: 19.7 },
  { name: "البندق نيء/محمص", category: "مكسرات", portion: "100 جم", carbs: 17.6 },
  { name: "اللوز", category: "مكسرات", portion: "عدد واحد", carbs: 0.2 },
  { name: "زبدة الفول السوداني", category: "مكسرات", portion: "ملعقة طعام", carbs: 3 },
  { name: "سمسم محمص", category: "مكسرات", portion: "100 جم", carbs: 26 },
  { name: "سمسم محمص", category: "مكسرات", portion: "ملعقة طعام", carbs: 2.3 },
  { name: "سمسم نيء", category: "مكسرات", portion: "100 جم", carbs: 11.73 },
  { name: "صنوبر", category: "مكسرات", portion: "كوب", carbs: 17.66 },
  { name: "طحينة سائلة", category: "مكسرات", portion: "ملعقة طعام", carbs: 3.2 },
  { name: "عين ال ل", category: "مكسرات", portion: "100 جم", carbs: 14 },
  { name: "عين ال ل مقطع", category: "مكسرات", portion: "كوب", carbs: 16 },
  { name: "فستق نيء/محمص", category: "مكسرات", portion: "100 جم", carbs: 27 },
  { name: "فستق نيء/محمص", category: "مكسرات", portion: "عدد واحد", carbs: 0.2 },
  { name: "فستق نيء/محمص", category: "مكسرات", portion: "كوب", carbs: 32.9 },
  { name: "فول سوداني نيء/محمص", category: "مكسرات", portion: "100 جم", carbs: 21.5 },
  { name: "فول سوداني نيء/محمص", category: "مكسرات", portion: "عدد واحد", carbs: 0.2 },
  { name: "فول سوداني نيء/محمص", category: "مكسرات", portion: "كوب", carbs: 31.1 },
  { name: "كاجو", category: "مكسرات", portion: "100 جم", carbs: 30.2 },
  { name: "كاجو غير مملح", category: "مكسرات", portion: "40 حبة", carbs: 12 },
  { name: "نوتيل", category: "مكسرات", portion: "ملعقة طعام", carbs: 11 },
  // منتجات ألبان
  { name: "1 كوب زبادي قليل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "1 كوب زبادي كامل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "1 كوب زبادي منزوع الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "1 كوب لبن قليل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "1 كوب لبن كامل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "1 كوب لبن منزوع الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "ثلث كوب حليب جاف قليل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "ثلث كوب حليب جاف كامل الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "ثلث كوب حليب جاف منزوع الدسم", category: "منتجات ألبان", portion: "حصة (1)", carbs: 12 },
  { name: "جبن بارميزان", category: "منتجات ألبان", portion: "حصة (1)", carbs: 4 },
  { name: "جبن رومي/جوده", category: "منتجات ألبان", portion: "حصة (1)", carbs: 2 },
  { name: "جبن شيدر", category: "منتجات ألبان", portion: "حصة (1)", carbs: 1.3 },
  { name: "جبن قريش", category: "منتجات ألبان", portion: "حصة (1)", carbs: 3 },
  { name: "جبن كريم/قابل للفرد", category: "منتجات ألبان", portion: "حصة (1)", carbs: 3 },
  { name: "جبن ماسكاربون", category: "منتجات ألبان", portion: "حصة (1)", carbs: 2 },
  { name: "حليب الام", category: "منتجات ألبان", portion: "كوب", carbs: 17 },
  { name: "حليب سادة", category: "منتجات ألبان", portion: "كوب", carbs: 12.8 },
  { name: "حليب شوكولتة", category: "منتجات ألبان", portion: "كوب", carbs: 26 },
  { name: "دانو حليب مجفف", category: "منتجات ألبان", portion: "ملعقة صغيرة", carbs: 7.5 },
  { name: "زبادي سادة", category: "منتجات ألبان", portion: "100 جم", carbs: 8 },
  { name: "زبادي فواكه", category: "منتجات ألبان", portion: "100 جم", carbs: 18 },
  { name: "لبن رايب", category: "منتجات ألبان", portion: "كوب", carbs: 12 },
  { name: "لبنة", category: "منتجات ألبان", portion: "100 جم", carbs: 5 },
  { name: "مغرفة صغيرة آيس كريم كاراميل", category: "منتجات ألبان", portion: "عدد واحد", carbs: 35 },
  { name: "مغرفة صغيرة آيس كريم شوكولتة", category: "منتجات ألبان", portion: "100 جم", carbs: 28 },
  { name: "مغرفة صغيرة آيس كريم فانيل", category: "منتجات ألبان", portion: "100 جم", carbs: 23 },
  // منتجات السوبر ماركت
  { name: "Loacker Hazelnut", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 27 },
  { name: "Loacker Hazelnut", category: "منتجات السوبر ماركت", portion: "قطعة", carbs: 3.4 },
  { name: "أيس كريم NESTLES POPS وزن    80", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 23 },
  { name: "اًّيس كريم", category: "منتجات السوبر ماركت", portion: "ح  أكبر", carbs: 30 },
  { name: "باكو شمعدان 25", category: "منتجات السوبر ماركت", portion: "2 صابع", carbs: 15 },
  { name: "باكو ميني مولتو", category: "منتجات السوبر ماركت", portion: "4 قطع", carbs: 30 },
  { name: "بسكو مصر الوزن 30    4 قطع Wafers", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 16.5 },
  { name: "بسكو مصر الوزن 30    4 قطع Wafers", category: "منتجات السوبر ماركت", portion: "قطعة", carbs: 4.1 },
  { name: "توبليرون وزن 35   Toblerone", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 21 },
  { name: "توت وكيك 50", category: "منتجات السوبر ماركت", portion: "قطعة", carbs: 30 },
  { name: "توت وكيك كاكاو 50", category: "منتجات السوبر ماركت", portion: "قطعة", carbs: 30 },
  { name: "جهينة مكس أي نوع", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 23 },
  { name: "جهينة مكس أي نوع", category: "منتجات السوبر ماركت", portion: "مل100", carbs: 11.5 },
  { name: "دروو باوند كيك زبده 55    Droo", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 38.5 },
  { name: "دوريتوز", category: "منتجات السوبر ماركت", portion: "100 جم", carbs: 65 },
  { name: "دوريتوس بطعمين وزن 52", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 30 },
  { name: "سامبا زرقاء 25", category: "منتجات السوبر ماركت", portion: "3 اصابع", carbs: 15 },
  { name: "شيبسي وزن 30", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 15.3 },
  { name: "شيتوس X&O's أو STARSوزن 36", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 21.5 },
  { name: "شيتوس العادي وزن 36", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 13.7 },
  { name: "شيتوس،منتج ذرة فشار بالملح وزن 35", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 13.3 },
  { name: "فول سوداني ديليتس المغطى بطبقة مقرمشة 50", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 22.5 },
  { name: "كيك مولتو 40", category: "منتجات السوبر ماركت", portion: "قطعة", carbs: 23 },
  { name: "لبن بالشيكوالتة /فواكه 200 ملل", category: "منتجات السوبر ماركت", portion: "علبة", carbs: 30 },
  { name: "لبن جينو بالشوكولاتة 125مل", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 16.25 },
  { name: "لبن رايب جهينة", category: "منتجات السوبر ماركت", portion: "مل100", carbs: 4.9 },
  { name: "لبن رايب جهينة 250 مل", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 12.5 },
  { name: "هوهوز جامبو وزن 40    jumBo HoHos", category: "منتجات السوبر ماركت", portion: "عبوة", carbs: 28.5 },
  // نشويات
  { name: "أرز أسمر مطهي", category: "نشويات", portion: "كوب", carbs: 45 },
  { name: "أرز مطهي طويل الحبة", category: "نشويات", portion: "كوب", carbs: 44 },
  { name: "أرز مطهي قصير/متوسط الحبة", category: "نشويات", portion: "كوب", carbs: 60 },
  { name: "أرز مطهي قصير/متوسط الحبة", category: "نشويات", portion: "ملعقة طعام", carbs: 7 },
  { name: "مكرونة رافيولي محشو باللحم", category: "نشويات", portion: "100 جم", carbs: 26 },
  { name: "مكرونة سباقيتي مع صوص اللحم", category: "نشويات", portion: "100 جم", carbs: 21 },
  { name: "نشا ذرة", category: "نشويات", portion: "ملعقة طعام", carbs: 7 },
  // هارديز
  { name: "هارديز - بطاطس مقلية- صغير", category: "هارديز", portion: "عبوة", carbs: 45 },
  { name: "هارديز - بطاطس مقلية- كبير", category: "هارديز", portion: "عبوة", carbs: 65 },
  { name: "هارديز - بطاطس مقلية- وسط", category: "هارديز", portion: "عبوة", carbs: 60 },
  { name: "هارديز - بطاطس مقلية-وجبة أطفال", category: "هارديز", portion: "عبوة", carbs: 30 },
  { name: "هارديز - كوكيز", category: "هارديز", portion: "قطعة", carbs: 44 },
  { name: "هارديز - كيكة شيكولتة", category: "هارديز", portion: "قطعة", carbs: 56 },
  { name: "هارديز -وجبة أطفال ، 2 قطعة فراخ", category: "هارديز", portion: "وجبة", carbs: 36 },
  { name: "هارديز -وجبة أطفال ، ساندوتش", category: "هارديز", portion: "وجبة", carbs: 60 },
  { name: "هارديز- برجر جبن", category: "هارديز", portion: "عدد واحد", carbs: 32 },
  { name: "هارديز- برجر جبن دبل", category: "هارديز", portion: "عدد واحد", carbs: 34 },
  { name: "هارديز- بطاطس حلقات كريسب - وسط", category: "هارديز", portion: "عبوة", carbs: 52 },
  { name: "هارديز- بطاطس حلقات كريسب -صغير", category: "هارديز", portion: "عبوة", carbs: 43 },
  { name: "هارديز- بيج شيف", category: "هارديز", portion: "عدد واحد", carbs: 36 },
  { name: "هارديز- فراخ فيليه", category: "هارديز", portion: "عدد واحد", carbs: 72 },
  { name: "هارديز- مشروم اند سويس", category: "هارديز", portion: "عدد واحد", carbs: 47 },
  { name: "هارديز-بطاطس حلقات كريسب - كبير", category: "هارديز", portion: "عبوة", carbs: 60 },
  { name: "هارديز-تشيكن BBQ", category: "هارديز", portion: "عدد واحد", carbs: 54 },
  { name: "هارديز-تشيكن تندرز", category: "هارديز", portion: "قطعة", carbs: 4.3 },
];
