import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { LogEntry } from "./api";
import { classifyBG } from "./calc";
import { computeStreak } from "./gamification";

// jsPDF's built-in fonts (Helvetica/Times/Courier) only cover Latin glyphs, so the
// report is always generated in English regardless of the app's active language —
// Arabic text would render as empty boxes without embedding a custom font.
const TYPE_LABEL: Record<LogEntry["type"], string> = {
  meal: "Meal dose",
  mealCorrection: "Meal + correction",
  correction: "Correction dose",
  hypo: "Low BG treated",
  bg: "Glucose reading",
};

const NAVY: [number, number, number] = [37, 99, 235];
const SLATE: [number, number, number] = [100, 116, 139];

export function buildReportPdf({
  patientName,
  units,
  entries,
}: {
  patientName: string;
  units: "mgdl" | "mmol";
  entries: LogEntry[];
}): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;
  const unitLabel = units === "mmol" ? "mmol/L" : "mg/dL";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...NAVY);
  doc.text("GlucoDose Glucose Report", marginX, 48);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...SLATE);
  doc.text(`Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, marginX, 66);
  doc.text(`Patient: ${patientName || "—"}`, marginX, 80);

  const cutoffMs = Date.now() - 14 * 24 * 60 * 60 * 1000;
  const readings = entries.filter((e) => e.timestamp >= cutoffMs && e.currentBG !== undefined);
  const inRangeCount = readings.filter((e) => classifyBG(e.currentBG!, units) === "inRange").length;
  const tirPct = readings.length ? Math.round((inRangeCount / readings.length) * 100) : 0;
  const avgBG = readings.length ? Math.round(readings.reduce((sum, e) => sum + (e.currentBG ?? 0), 0) / readings.length) : null;
  const streak = computeStreak(entries);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text("14-Day Summary", marginX, 112);

  autoTable(doc, {
    startY: 120,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 4, textColor: [30, 30, 30] },
    body: [
      ["Time in range", `${tirPct}%`],
      ["Average glucose", avgBG !== null ? `${avgBG} ${unitLabel}` : "No data"],
      ["Readings logged (14d)", String(readings.length)],
      ["Current day streak", String(streak)],
    ],
    margin: { left: marginX, right: marginX },
  });

  const afterSummaryY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 26;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text("Log Entries", marginX, afterSummaryY);

  const sorted = [...entries].sort((a, b) => b.timestamp - a.timestamp);
  const rows = sorted.map((e) => [
    new Date(e.timestamp).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }),
    TYPE_LABEL[e.type] ?? e.type,
    e.currentBG !== undefined ? `${e.currentBG}` : "—",
    e.carbs !== undefined ? `${e.carbs}g` : e.carbsNeeded !== undefined ? `${e.carbsNeeded}g` : "—",
    e.dose !== undefined ? `${e.dose}u` : "—",
    e.notes ?? "",
  ]);

  autoTable(doc, {
    startY: afterSummaryY + 8,
    head: [["Date", "Type", `BG (${unitLabel})`, "Carbs", "Dose", "Notes"]],
    body: rows.length ? rows : [["—", "—", "—", "—", "—", "No entries logged yet"]],
    styles: { fontSize: 9, cellPadding: 5 },
    headStyles: { fillColor: NAVY, textColor: 255 },
    alternateRowStyles: { fillColor: [246, 247, 249] },
    margin: { left: marginX, right: marginX },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...SLATE);
    doc.text(
      "Generated by GlucoDose. This report supports diabetes self-management and does not replace medical advice.",
      marginX,
      doc.internal.pageSize.getHeight() - 24,
      { maxWidth: pageWidth - marginX * 2 },
    );
  }

  return doc;
}
